export default {
  cardId: "03f138f65cb1411f9079893cce808953",
  cardSubType: "SELECT_PROVIDER_BY_OFFER_CARD",
  cardType: "REPORT_CARD",
  eventType: "DATA_DISPLAY",
  imageUrl:
    "https://cbu01.alicdn.com/img/ibank/O1CN011DeMsH1OHUUqXSGa3_!!4611686018427381392-0-overseas_pic.jpg",
  rawData: {
    offerInfo: {
      aiRequirementAnalysis: { isDisplay: false },
      offerList: [
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "✨客服响应率91%，表现优秀",
          ],
          coreAttributes: [
            {
              label: "颜色",
              value: "黑色,酒红色,粉红色,棕色,米色,绿色,玫红色,宝蓝,灰色",
            },
            { label: "功能", value: "吸湿排汗速干" },
            { label: "面料", value: "锦纶" },
            { label: "尺码", value: "S,M,L" },
            { label: "下装款式", value: "长裤" },
            { label: "裤长", value: "长裤" },
            { label: "材质成分", value: "90%锦纶10%氨纶" },
            { label: "品牌", value: "QIANGSHENG" },
            { label: "货号", value: "9K241" },
            { label: "上市年份季节", value: "2025年春季" },
            { label: "适用对象", value: "女性" },
          ],
          extraInfoDTO: { xl1y: 16444 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01Wv1ev21wALAE25bQL_!!2211589386267-0-cib.jpg",
          itemId: "708194150954",
          itemPrice: "22.0",
          offerDetailUrl: "https://detail.1688.com/offer/708194150954.html",
          providerInfo: {
            companyName: "浙江乾盛服饰有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2211589386267e2827",
            providerTags: [
              { tagName: "超级工厂", tagStyle: "SUPER_FACTORY" },
              { tagName: "实力商家", tagStyle: "POWER_FACTORY" },
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通5年", tagStyle: "GENERAL" },
            ],
            userId: "2211589386267",
          },
          providerKjCustomTags: [
            "Logo定制",
            "产品演示视频",
            "无痕发货",
            "来图加工",
            "来样加工",
            "清加工",
            "贴标服务",
          ],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 91.0,
              value: "91%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 59.0,
              value: "59%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 3.9,
              value: "3.9",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 1012.0,
              value: "1012",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 1907.0,
              value: "1907",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 457.0,
              value: "457",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 18.0,
              value: "18",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年销量",
              originValue: 16444.0,
              value: "1.6万+",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "浙江省金华市" },
          ],
          title: "瑜伽裤女高腰提臀弹力紧身运动收腹吸湿速干瑜伽裸感健身长裤",
        },
        {
          aiAttentions: [
            "✨48小时揽收率100%，表现优秀",
            "✨发货履约率100%，表现优秀",
          ],
          coreAttributes: [
            {
              label: "颜色",
              value:
                "浓缩咖啡Espresso coffee,海军蓝Navy blue,石墨灰Graphite Grey,黑色Black,安可拉红Encore red",
            },
            { label: "功能", value: "加绒保暖" },
            { label: "面料", value: "晓星" },
            { label: "尺码", value: "4/S,6/M,8/L,10/XL" },
            { label: "下装款式", value: "紧身裤" },
            { label: "裤长", value: "长裤" },
            { label: "材质成分", value: "氨纶" },
            { label: "品牌", value: "weixian" },
            { label: "货号", value: "CK12" },
            { label: "上市年份季节", value: "全年" },
            { label: "适用对象", value: "瑜伽运动跑步健身户外爬山" },
          ],
          extraInfoDTO: { xl1y: 20 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01PkXCtX27tBjYqBIkO_!!2664557854-0-cib.jpg",
          itemId: "886440921273",
          itemPrice: "43.0",
          offerDetailUrl: "https://detail.1688.com/offer/886440921273.html",
          providerInfo: {
            companyName: "义乌市伟贤服饰有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2664557854ffaac",
            providerTags: [
              { tagName: "实力商家", tagStyle: "POWER_FACTORY" },
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通10年", tagStyle: "GENERAL" },
            ],
            userId: "2664557854",
          },
          providerKjCustomTags: [
            "产品演示视频",
            "包工包料",
            "材质定制",
            "来图加工",
            "来样加工",
            "清加工",
            "资质认证定制",
          ],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 99.0,
              value: "99%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 56.0,
              value: "56%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 4.2,
              value: "4.2",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 2853.0,
              value: "2853",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 8102.0,
              value: "8102",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 311.0,
              value: "311",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 5.0,
              value: "5",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年销量",
              originValue: 20.0,
              value: "20",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            {
              code: "o-lyl",
              label: "发货履约率",
              originValue: 100.0,
              value: "100%",
            },
            {
              code: "o-lsl",
              label: "48小时揽收率",
              originValue: 100.0,
              value: "100%",
            },
            { code: "fhd", label: "发货地", value: "浙江省金华市" },
          ],
          title: "加绒秋冬高腰设计瑜伽裤女收腹长裤打底保暖跑步运动紧身裤",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "✨综合服务分3.9，表现良好",
          ],
          coreAttributes: [
            { label: "货源类别", value: "现货" },
            { label: "产品类别", value: "长裤" },
            { label: "功能", value: "超强弹性" },
            { label: "品牌", value: "天宏" },
            { label: "适用性别", value: "女" },
            { label: "图案", value: "纯色" },
            { label: "误差范围", value: "1~2cm" },
            { label: "适合季节", value: "冬季,秋季" },
            { label: "是否外贸", value: "否" },
            { label: "是否库存", value: "是" },
            { label: "库存类型", value: "整单" },
            { label: "面料名称", value: "化纤类混纺" },
            { label: "面料成分", value: "氨纶" },
            { label: "面料成分含量", value: "10" },
            { label: "里料名称", value: "化纤类混纺" },
            { label: "里料成分", value: "锦纶/尼龙" },
            { label: "里料成分含量", value: "90" },
            { label: "货号", value: "8261" },
            { label: "颜色", value: "黑色" },
            { label: "尺码", value: "S,M,L" },
            {
              label: "适用场景",
              value:
                "跑步运动,健身器材,健身美体,骑行运动,冰雪运动,极限挑战,徒步登山野营,射击运动,舞蹈运动",
            },
            {
              label: "主要下游平台",
              value: "ebay,亚马逊,wish,速卖通,独立站,LAZADA",
            },
            {
              label: "主要销售地区",
              value: "非洲,欧洲,南美,东南亚,北美,东北亚,中东",
            },
            { label: "有可授权的自有品牌", value: "是" },
            { label: "是否跨境出口专供货源", value: "是" },
            { label: "适用人群", value: "女性" },
            { label: "款号", value: "8261" },
            { label: "运动户外项目", value: "健身" },
            { label: "上市时间", value: "2025年夏季" },
          ],
          extraInfoDTO: { xl1y: 2 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01fcRhhv1GPieF1LeNd_!!2201493700615-0-cib.jpg",
          itemId: "945157056473",
          itemPrice: "22.0",
          offerDetailUrl: "https://detail.1688.com/offer/945157056473.html",
          providerInfo: {
            companyName: "义乌市天宏服饰有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-220149370061563cb1",
            providerTags: [
              { tagName: "实力商家", tagStyle: "POWER_FACTORY" },
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通7年", tagStyle: "GENERAL" },
            ],
            userId: "2201493700615",
          },
          providerKjCustomTags: [
            "Logo定制",
            "产品演示视频",
            "包工包料",
            "无痕发货",
            "来图加工",
            "来样加工",
            "贴标服务",
            "颜色定制",
          ],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 88.0,
              value: "88%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 55.0,
              value: "55%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 3.9,
              value: "3.9",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 879.0,
              value: "879",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 1773.0,
              value: "1773",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 172.0,
              value: "172",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 9.0,
              value: "9",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年销量",
              originValue: 2.0,
              value: "<10",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "浙江省金华市" },
          ],
          title: "高腰提臀瑜伽裤女速干高弹力收腹紧身裤运动裤跑步训练健身裤长裤",
        },
        {
          aiAttentions: [
            "✨近一年全网销量1.6万+，全场最高",
            "✨品质退款率0%，全场最低",
          ],
          coreAttributes: [
            {
              label: "颜色",
              value: "黑色,酒红色,粉红色,棕色,米色,绿色,玫红色,宝蓝",
            },
            { label: "功能", value: "吸湿排汗速干" },
            { label: "面料", value: "锦纶" },
            { label: "尺码", value: "S,M,L" },
            { label: "下装款式", value: "长裤" },
            { label: "裤长", value: "长裤" },
            { label: "材质成分", value: "90%锦纶10%氨纶" },
            { label: "品牌", value: "QIANGSHENG" },
            { label: "货号", value: "9K241" },
            { label: "上市年份季节", value: "2023年春季" },
            { label: "适用对象", value: "女性" },
          ],
          extraInfoDTO: { qwXl1y: 16444 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01Wv1ev21wALAE25bQL_!!2211589386267-0-cib.jpg",
          itemId: "956003924691",
          itemPrice: "27.41",
          offerDetailUrl: "https://detail.1688.com/offer/956003924691.html",
          providerInfo: {
            companyName: "杭州壹陆捌捌采建电子商务有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-221864942454127e8e",
            providerTags: [
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通2年", tagStyle: "GENERAL" },
            ],
            userId: "2218649424541",
          },
          providerKjCustomTags: [
            "Logo定制",
            "产品演示视频",
            "包装定制",
            "外文素材",
            "拥有专利",
            "无字素材图",
            "无痕发货",
            "材质定制",
            "清加工",
            "贴标服务",
            "贴箱唛服务",
            "资质认证定制",
            "颜色定制",
          ],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 54.0,
              value: "54%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 34.0,
              value: "34%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 3.1,
              value: "3.1",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 1006241.0,
              value: "1006241",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 2887522.0,
              value: "2887522",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 230816.0,
              value: "230816",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 40743.0,
              value: "40743",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 16444.0,
              value: "1.6万+",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "浙江省金华市" },
          ],
          title: "瑜伽裤女高腰提臀弹力紧身运动健身收腹吸湿排汗速干瑜伽长裤",
        },
        {
          aiAttentions: [
            "❗客服响应率26%，表现不佳",
            "❗综合服务分2.9，表现不佳",
          ],
          coreAttributes: [
            { label: "货号", value: "AL904905804424" },
            { label: "品牌", value: "其他" },
            { label: "面料名称", value: "雪尼尔" },
            { label: "主面料成分", value: "氨纶" },
            { label: "主面料成分2", value: "其他" },
            { label: "款式", value: "铅笔裤" },
            { label: "裤长", value: "长裤" },
            { label: "流行元素", value: "其他" },
            { label: "上市年份/季节", value: "2025年春季" },
            {
              label: "颜色",
              value:
                "Black,Blue,Sky Blue,Brown,Gray,green,Ivory,Orange,Pink,purple,Red,grey top,yellow top,Rose Red,navy,black top,red top,Mint,1pc Cleaning tool",
            },
            { label: "尺码", value: "XS,S,M,L,XL,XXL,XXXL" },
            { label: "风格类型", value: "私服名媛" },
            { label: "主面料成分含量", value: "30%以下" },
            { label: "风格", value: "御姐风" },
            { label: "裤型", value: "大喇叭型" },
            { label: "是否跨境货源", value: "否" },
            { label: "产品类别", value: "牛仔裤" },
            { label: "工艺", value: "其他/other" },
          ],
          extraInfoDTO: { qwXl1y: 1873, xl1y: 0 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01TWlGsP1i7DsJXPvqz_!!2219487524365-0-cib.jpg",
          itemId: "911039712185",
          itemPrice: "22.29",
          offerDetailUrl: "https://detail.1688.com/offer/911039712185.html",
          providerInfo: {
            companyName: "亭湖区泽胜福百货经营部(个体工商户)",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2219487524365146d2",
            providerTags: [{ tagName: "诚信通1年", tagStyle: "GENERAL" }],
            userId: "2219487524365",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 1.0,
              value: "1%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 26.0,
              value: "26%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 28.0,
              value: "28%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 2.9,
              value: "2.9",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 70.0,
              value: "70",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 305.0,
              value: "305",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 3524.0,
              value: "3524",
            },
            { code: "p-sx30d", label: "近30天上新", value: "-" },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 1873.0,
              value: "1873",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "浙江省杭州市" },
          ],
          title: "astic High Waist Legging Breathable Slim Pants indoor Sports",
        },
        {
          aiAttentions: [
            "✨商品价格¥8.8，全场最低",
            "✨48小时揽收率100%，全场最佳",
          ],
          coreAttributes: [
            { label: "颜色", value: "黑色,白色,红色,蓝色,荧光绿" },
            { label: "功能", value: "高弹透气速干" },
            { label: "面料", value: "涤纶" },
            { label: "尺码", value: "S,M,L,XL,XXL" },
            { label: "下装款式", value: "紧身" },
            { label: "裤长", value: "九分裤" },
            { label: "材质成分", value: "95" },
            { label: "品牌", value: "宏越服饰" },
            { label: "货号", value: "2020" },
            { label: "上市年份季节", value: "夏季" },
            { label: "适用对象", value: "女性" },
          ],
          extraInfoDTO: { qwXl1y: 1395, xl1y: 289 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01gcwTeB1DesmmYzczQ_!!2217542690242-0-cib.jpg",
          itemId: "775731950442",
          itemPrice: "8.8",
          offerDetailUrl: "https://detail.1688.com/offer/775731950442.html",
          providerInfo: {
            companyName: "玉林市宏越服饰有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-22175426902422a2fd",
            providerTags: [
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通2年", tagStyle: "GENERAL" },
            ],
            userId: "2217542690242",
          },
          providerKjCustomTags: ["Logo定制", "颜色定制"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 97.0,
              value: "97%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 57.0,
              value: "57%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 4.4,
              value: "4.4",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 421.0,
              value: "421",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 700.0,
              value: "700",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 75.0,
              value: "75",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 1.0,
              value: "1",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 1395.0,
              value: "1395",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            {
              code: "o-lyl",
              label: "发货履约率",
              originValue: 100.0,
              value: "100%",
            },
            {
              code: "o-lsl",
              label: "48小时揽收率",
              originValue: 100.0,
              value: "100%",
            },
            { code: "fhd", label: "发货地", value: "广西壮族自治区玉林市" },
          ],
          title: "紧身长裤 运动跑步舞蹈训练瑜伽裤显瘦 速干透气高弹力健身长裤",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "❗90天回头率0%，表现较差",
          ],
          coreAttributes: [
            { label: "货源类别", value: "订货" },
            { label: "产品类别", value: "裤" },
            { label: "功能", value: "透气" },
            { label: "品牌", value: "YOKLIL" },
            { label: "适用性别", value: "女" },
            { label: "裤长", value: "长裤" },
            { label: "图案", value: "纯色" },
            { label: "误差范围", value: "1~2cm" },
            { label: "适合季节", value: "夏季,冬季,春季,秋季" },
            { label: "是否外贸", value: "否" },
            { label: "最快出货时间", value: "8-15天" },
            { label: "面料名称", value: "锦纶" },
            { label: "面料成分", value: "锦纶/尼龙" },
            { label: "面料成分含量", value: "90" },
            { label: "里料名称", value: "咨询卖家" },
            { label: "里料成分", value: "锦纶/尼龙" },
            { label: "里料成分含量", value: "90" },
            { label: "货号", value: "瑜伽裤" },
            { label: "颜色", value: "黑色" },
            { label: "尺码", value: "S,M,L,XL" },
            {
              label: "适用场景",
              value:
                "跑步运动,健身器材,健身美体,运动潮流,骑行运动,徒步登山野营,舞蹈运动,足篮排运动",
            },
            { label: "是否跨境出口专供货源", value: "否" },
            { label: "下装款式", value: "束腿裤" },
            { label: "服装版型", value: "紧身" },
            { label: "专利类型", value: "无" },
            { label: "适用人群", value: "成人" },
          ],
          extraInfoDTO: { qwXl1y: 669 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/13083987162_2055243490.jpg",
          itemId: "607193979402",
          itemPrice: "38.0",
          offerDetailUrl: "https://detail.1688.com/offer/607193979402.html",
          providerInfo: {
            companyName: "杭州圣远服饰有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=brucewang183",
            providerTags: [
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通15年", tagStyle: "GENERAL" },
            ],
            userId: "986221503",
          },
          providerKjCustomTags: ["包工包料", "来图加工", "来样加工", "清加工"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 2.5,
              value: "2.5",
            },
            { code: "p-dd30d", label: "30天订单", value: "-" },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 3.0,
              value: "3",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 40.0,
              value: "40",
            },
            { code: "p-sx30d", label: "近30天上新", value: "-" },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 200.0,
              value: "200件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 669.0,
              value: "669",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "浙江省杭州市" },
          ],
          title: "紧身运动长裤女春秋长款瑜伽速干训练跑步健身黑色运动裤透气速干",
        },
        {
          aiAttentions: [
            "✨90天回头率71%，全场最佳",
            "✨品质退款率0%，表现优秀",
          ],
          coreAttributes: [
            { label: "货源类别", value: "现货" },
            { label: "是否库存", value: "是" },
            { label: "适合季节", value: "夏季,春季,秋季" },
            { label: "适用性别", value: "女" },
            { label: "适用年龄段", value: "成年" },
            { label: "风格", value: "运动休闲,弹力,修身款" },
            { label: "面料名称", value: "化纤类混纺" },
            { label: "面料成分", value: "锦纶/尼龙" },
            { label: "面料成分含量", value: "75%" },
            { label: "有无内胆", value: "无内胆" },
            { label: "货号", value: "K591" },
            { label: "颜色", value: "紫色,黑色,灰色" },
            { label: "尺码", value: "M,L,XL,2XL,3XL,4XL" },
            { label: "吊牌价", value: "168元" },
            { label: "产品类别", value: "裤" },
          ],
          extraInfoDTO: { xl1y: 165 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01MzPoc61KzgBGCapav_!!2208548981235-0-cib.jpg",
          itemId: "897791433351",
          itemPrice: "39.0",
          offerDetailUrl: "https://detail.1688.com/offer/897791433351.html",
          providerInfo: {
            companyName: "中山市小榄镇乐动力制衣厂",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-22085489812356c55d",
            providerTags: [
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通6年", tagStyle: "GENERAL" },
            ],
            userId: "2208548981235",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 43.0,
              value: "43%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 71.0,
              value: "71%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 4.4,
              value: "4.4",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 705.0,
              value: "705",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 148.0,
              value: "148",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 122.0,
              value: "122",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 3.0,
              value: "3",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "-" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年销量",
              originValue: 165.0,
              value: "165",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "广东省中山市" },
          ],
          title: "瑜伽裤高腰提臀运动健身裤弹力修身显瘦",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "✨综合服务分4.1，表现优秀",
          ],
          coreAttributes: [
            { label: "货源类别", value: "现货" },
            { label: "适用性别", value: "女" },
            { label: "适合季节", value: "冬季,春季,秋季" },
            { label: "面料名称", value: "莫代尔" },
            { label: "面料成分", value: "锦纶/尼龙" },
            { label: "面料成分含量", value: "90" },
            { label: "颜色", value: "混色发货" },
            { label: "尺码", value: "混码" },
          ],
          extraInfoDTO: {},
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01AyvXUJ1YYZF9fFIzH_!!979183071-0-cib.jpg",
          itemId: "769237600232",
          itemPrice: "10.9",
          offerDetailUrl: "https://detail.1688.com/offer/769237600232.html",
          providerInfo: {
            companyName: "义乌市三西野贸易有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=tianzhong688",
            providerTags: [{ tagName: "诚信通15年", tagStyle: "GENERAL" }],
            userId: "979183071",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 86.0,
              value: "86%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 65.0,
              value: "65%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 4.1,
              value: "4.1",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 22.0,
              value: "22",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 55.0,
              value: "55",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 432.0,
              value: "432",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 41.0,
              value: "41",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 100.0,
              value: "100件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [{ code: "o-xl", label: "近一年销量", value: "<10" }],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "浙江金华" },
          ],
          title: "售价不低于29元~W49#NUR D**原单 高强度瑜伽裤0.21kg",
        },
        {
          aiAttentions: [
            "✨综合服务分4.6，全场最佳",
            "✨客服响应率100%，全场最佳",
          ],
          coreAttributes: [
            { label: "货源类别", value: "现货" },
            { label: "品牌", value: "YL" },
            { label: "适用运动", value: "瑜伽，跑步，调操" },
            { label: "适用性别", value: "女" },
            { label: "货号", value: "312" },
            { label: "适合季节", value: "冬季,春季,秋季" },
            { label: "系列", value: "公主系列" },
            { label: "形象", value: "火腿" },
            { label: "面料名称", value: "化纤类混纺" },
            { label: "面料成分", value: "锦纶/尼龙" },
            { label: "面料成分含量", value: "82" },
            { label: "里料成分", value: "聚酯纤维（涤纶）" },
            { label: "里料名称", value: "化纤类混纺" },
            { label: "里料成分含量", value: "95" },
            {
              label: "适用场景",
              value: "跑步运动,健身器材,健身美体,骑行运动,舞蹈运动",
            },
            { label: "颜色", value: "黑色,浅灰色,灰蓝" },
            { label: "尺码", value: "M,L,XL,XXL,XXXL,4XL" },
            {
              label: "主要下游平台",
              value: "ebay,亚马逊,wish,速卖通,独立站,LAZADA",
            },
            { label: "主要销售地区", value: "东南亚,东北亚,中东" },
            { label: "有可授权的自有品牌", value: "否" },
            { label: "是否跨境出口专供货源", value: "是" },
            { label: "专利类型", value: "无" },
            { label: "外贸出口认证", value: "无" },
          ],
          extraInfoDTO: {},
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN014Tyarz22cAiY4uz30_!!3684057140-0-cib.jpg",
          itemId: "698253970189",
          itemPrice: "32.0",
          offerDetailUrl: "https://detail.1688.com/offer/698253970189.html",
          providerInfo: {
            companyName: "兴城市艺隆制衣厂",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-368405714086fd2",
            providerTags: [
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通8年", tagStyle: "GENERAL" },
            ],
            userId: "3684057140",
          },
          providerKjCustomTags: [
            "Logo定制",
            "包工包料",
            "材质定制",
            "来图加工",
            "来样加工",
          ],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 100.0,
              value: "100%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 57.0,
              value: "57%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 4.6,
              value: "4.6",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 75.0,
              value: "75",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 373.0,
              value: "373",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 1922.0,
              value: "1922",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 3.0,
              value: "3",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 2.0,
              value: "2件起批",
            },
            { code: "o-fw", label: "服务", value: "-" },
          ],
          salesInfos: [{ code: "o-xl", label: "近一年销量", value: "<10" }],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "辽宁省葫芦岛市" },
          ],
          title: "瑜伽裤女高腰弹力裤运动健身跑步机紧身长裤塑身显瘦遮肚亚马逊款",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "✨客服响应率98%，响应及时",
          ],
          coreAttributes: [
            { label: "货源类别", value: "现货" },
            { label: "品牌", value: "/" },
            { label: "适用性别", value: "女" },
            { label: "货号", value: "K901" },
            { label: "适合季节", value: "夏季,春季,秋季" },
            { label: "面料名称", value: "锦纶" },
            { label: "面料成分", value: "聚酯纤维（涤纶）" },
            { label: "面料成分含量", value: "90%涤纶10%氨纶" },
            { label: "颜色", value: "黑色" },
            { label: "尺码", value: "S,M,L" },
            { label: "适用对象", value: "女性" },
            { label: "服装版型", value: "修身" },
          ],
          extraInfoDTO: { qwXl1y: 1280, xl1y: 16 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN017ah8VL1CRlvppb8vz_!!2217775650078-0-cib.jpg",
          itemId: "896242284363",
          itemPrice: "16.0",
          offerDetailUrl: "https://detail.1688.com/offer/896242284363.html",
          providerInfo: {
            companyName: "义乌龙周纺织有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-22177756500787b14d",
            providerTags: [
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通2年", tagStyle: "GENERAL" },
            ],
            userId: "2217775650078",
          },
          providerKjCustomTags: ["包工包料", "来图加工", "来样加工", "清加工"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 98.0,
              value: "98%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 59.0,
              value: "59%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 4.5,
              value: "4.5",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 9.0,
              value: "9",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 21.0,
              value: "21",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 38.0,
              value: "38",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 1.0,
              value: "1",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 1280.0,
              value: "1280",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "浙江省金华市" },
          ],
          title: "无缝黑色瑜伽裤提臀高腰跑步运动裤女骑行紧身性感健身打底长裤",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "✨综合服务分3.9，表现良好",
          ],
          coreAttributes: [
            { label: "货源类别", value: "现货" },
            { label: "品牌", value: "其他" },
            { label: "适用运动", value: "跑步健身瑜伽普拉提" },
            { label: "适用性别", value: "女" },
            { label: "货号", value: "9k448" },
            { label: "适合季节", value: "春季,秋季" },
            { label: "系列", value: "星战" },
            { label: "形象", value: "闪电" },
            { label: "面料名称", value: "化纤类混纺" },
            { label: "面料成分", value: "锦纶/尼龙" },
            { label: "面料成分含量", value: "锦纶/尼龙" },
            { label: "里料成分", value: "锦纶/尼龙" },
            { label: "里料名称", value: "化纤类混纺" },
            { label: "里料成分含量", value: "90%" },
            { label: "适用场景", value: "跑步运动" },
            { label: "颜色", value: "黑色,藏青色,深灰色" },
            { label: "尺码", value: "S,M,L" },
            { label: "是否跨境出口专供货源", value: "是" },
            { label: "专利类型", value: "无" },
          ],
          extraInfoDTO: { qwXl1y: 730, xl1y: 5 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01aLnkGP2GDoQwAhI6G_!!2207961318982-0-cib.jpg",
          itemId: "813740056026",
          itemPrice: "19.0",
          offerDetailUrl: "https://detail.1688.com/offer/813740056026.html",
          providerInfo: {
            companyName: "义乌市品洛服饰有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2207961318982031d4",
            providerTags: [{ tagName: "诚信通2年", tagStyle: "GENERAL" }],
            userId: "2207961318982",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 88.0,
              value: "88%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 58.0,
              value: "58%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 3.9,
              value: "3.9",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 116.0,
              value: "116",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 163.0,
              value: "163",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 141.0,
              value: "141",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 40.0,
              value: "40",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 730.0,
              value: "730",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "浙江省金华市" },
          ],
          title: "欧美瑜伽裤女高腰提臀高级感健身运动普拉提跑步裤子外穿瑜伽裤",
        },
        {
          aiAttentions: [
            "❗品质退款率15%，表现较差",
            "❗客服响应率37%，表现不佳",
          ],
          coreAttributes: [
            { label: "面料名称", value: "TR面料" },
            { label: "图案", value: "其他" },
            { label: "工艺", value: "其他" },
            { label: "产地", value: "中国" },
            { label: "款式", value: "其他" },
            { label: "组合形式", value: "单件" },
            { label: "裙长", value: "中裙" },
            { label: "裙型", value: "其他" },
            { label: "领型", value: "POLO领" },
            { label: "袖型", value: "公主袖" },
            { label: "袖长", value: "七分袖" },
            { label: "腰型", value: "松紧腰" },
            { label: "流行元素", value: "纯色" },
            { label: "上市年份/季节", value: "2025年春季" },
            { label: "主面料成分", value: "PVC" },
            { label: "主面料成分2", value: "其他" },
            { label: "货号", value: "jd601099614302013" },
            { label: "品牌", value: "其他" },
            {
              label: "颜色",
              value:
                "Grey+Black,Army Green+Black,VibrantBlue+Black,Wine Red+Black,Purple+black,Coffee+Black,Black+black,a white T-shirt",
            },
            { label: "尺码", value: "XS,S,M,L,XL,XXL" },
            { label: "风格类型", value: "文艺复古" },
            { label: "门襟", value: "无扣" },
            { label: "主面料成分含量", value: "30%以下" },
            { label: "风格", value: "中国风" },
            { label: "裙类别", value: "连衣裙" },
            { label: "是否跨境货源", value: "否" },
            { label: "主面料成分2含量", value: "70%（含）-80%（不含）" },
          ],
          extraInfoDTO: { qwXl1y: 349, xl1y: 0 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01Km70sD1qOBTKC98EH_!!2219639425485-0-cib.jpg",
          itemId: "918409516258",
          itemPrice: "51.01",
          offerDetailUrl: "https://detail.1688.com/offer/918409516258.html",
          providerInfo: {
            companyName: "新沂市熙语绮百货店(个体工商户)",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2219639425485eb9ce",
            providerTags: [{ tagName: "诚信通1年", tagStyle: "GENERAL" }],
            userId: "2219639425485",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 15.0,
              value: "15%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 37.0,
              value: "37%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 37.0,
              value: "37%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 1.9,
              value: "1.9",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 124.0,
              value: "124",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 1656.0,
              value: "1656",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 3319.0,
              value: "3319",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 564.0,
              value: "564",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 349.0,
              value: "349",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "江苏省南京市" },
          ],
          title: "Two High-Elasticity Solid Color Fitness Yoga Leggings -",
        },
        {
          aiAttentions: [
            "❗客服响应率37%，表现不佳",
            "❗综合服务分2.4，表现不佳",
          ],
          coreAttributes: [
            { label: "面料名称", value: "雪尼尔" },
            { label: "主面料成分", value: "氨纶" },
            { label: "主面料成分2", value: "其他" },
            { label: "品牌", value: "其他" },
            { label: "货号", value: "jd601099872683861" },
            { label: "裤长", value: "三分裤" },
            { label: "款式", value: "其他" },
            { label: "厚薄", value: "中等" },
            { label: "图案", value: "其他" },
            { label: "流行元素", value: "其他" },
            { label: "上市年份/季节", value: "2025年春季" },
            { label: "是否一体裤", value: "否" },
            { label: "颜色", value: "Black,a white T-shirt" },
            { label: "尺码", value: "XS,S,M,L,XL,XXL" },
            { label: "主面料成分含量", value: "30%以下" },
            { label: "裤型", value: "宽松型" },
            { label: "是否跨境货源", value: "否" },
            { label: "产品类别", value: "打底裤,孕妇打底裤,一体裤" },
          ],
          extraInfoDTO: { qwXl1y: 132, xl1y: 0 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01z88mJN1iGNoIHZWaz_!!2219544454385-0-cib.jpg",
          itemId: "937760915780",
          itemPrice: "17.44",
          offerDetailUrl: "https://detail.1688.com/offer/937760915780.html",
          providerInfo: {
            companyName: "莱西市宇漫科贸易行(个体工商户)",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2219544454385142fc",
            providerTags: [{ tagName: "诚信通1年", tagStyle: "GENERAL" }],
            userId: "2219544454385",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 1.0,
              value: "1%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 37.0,
              value: "37%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 35.0,
              value: "35%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 2.4,
              value: "2.4",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 85.0,
              value: "85",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 322.0,
              value: "322",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 3749.0,
              value: "3749",
            },
            { code: "p-sx30d", label: "近30天上新", value: "-" },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 132.0,
              value: "132",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "浙江省杭州市" },
          ],
          title: "Women's High Waist Leggings Tummy Control Seams Yoga跨境",
        },
        {
          aiAttentions: [
            "❗综合服务分1.9，存在风险",
            "❗客服响应率35%，表现不佳",
          ],
          coreAttributes: [
            { label: "货号", value: "AL904905804424" },
            { label: "品牌", value: "其他" },
            { label: "面料名称", value: "雪尼尔" },
            { label: "主面料成分", value: "氨纶" },
            { label: "主面料成分2", value: "其他" },
            { label: "款式", value: "铅笔裤" },
            { label: "裤长", value: "长裤" },
            { label: "流行元素", value: "其他" },
            { label: "上市年份/季节", value: "2025年春季" },
            {
              label: "颜色",
              value:
                "Black,Blue,Sky Blue,Brown,Gray,green,Ivory,Orange,Pink,purple,Red,grey top,yellow top,Rose Red,navy,black top,red top,Mint,1pc Cleaning tool",
            },
            { label: "尺码", value: "XS,S,M,L,XL,XXL,XXXL" },
            { label: "风格类型", value: "私服名媛" },
            { label: "主面料成分含量", value: "30%以下" },
            { label: "风格", value: "御姐风" },
            { label: "裤型", value: "大喇叭型" },
            { label: "是否跨境货源", value: "否" },
            { label: "产品类别", value: "牛仔裤" },
            { label: "工艺", value: "其他/other" },
          ],
          extraInfoDTO: { qwXl1y: 50, xl1y: 0 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01dUoowP1GEj7g7ZXQw_!!2219532140591-0-cib.jpg",
          itemId: "910259163108",
          itemPrice: "22.29",
          offerDetailUrl: "https://detail.1688.com/offer/910259163108.html",
          providerInfo: {
            companyName: "莱西市聚通源贸易行（个体工商户）",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2219532140591b8127",
            providerTags: [{ tagName: "诚信通1年", tagStyle: "GENERAL" }],
            userId: "2219532140591",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 4.0,
              value: "4%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 35.0,
              value: "35%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 27.0,
              value: "27%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 1.9,
              value: "1.9",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 144.0,
              value: "144",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 369.0,
              value: "369",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 3870.0,
              value: "3870",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 552.0,
              value: "552",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 50.0,
              value: "50",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "江苏省南京市" },
          ],
          title: "astic High Waist Legging Breathable Slim Pants indoor Sports",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "❗客服响应率0%，表现不佳",
          ],
          coreAttributes: [
            {
              label: "颜色",
              value:
                "黑色扎染,深红色,橄榄绿,蓝,深灰迷彩,绿色扎染,闪蓝色,黑色,格兰尼塔粉,灰褐色,木槿紫,扎染烟墨色,灰鼠尾草色,宇宙蓝,海军蓝,黑檀色,深海军蓝,深紫色,热软糖棕",
            },
            { label: "功能", value: "裸感/透气/亲肤/高弹" },
            { label: "面料", value: "锦纶+氨纶" },
            { label: "尺码", value: "均码" },
            { label: "下装款式", value: "瑜伽裤" },
            { label: "裤长", value: "九分裤" },
            { label: "材质成分", value: "锦纶80+氨纶20" },
            { label: "货号", value: "YS01" },
            { label: "上市年份季节", value: "2024年夏季" },
            { label: "适用对象", value: "女" },
          ],
          extraInfoDTO: { qwXl1y: 24 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01YWzAZr270EDp9T5qJ_!!2219531667734-0-cib.jpg",
          itemId: "913279515291",
          itemPrice: "9999999.0",
          offerDetailUrl: "https://detail.1688.com/offer/913279515291.html",
          providerInfo: {
            companyName: "厦门永思睿工贸有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-221953166773495c59",
            providerTags: [
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通1年", tagStyle: "GENERAL" },
            ],
            userId: "2219531667734",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 2.5,
              value: "2.5",
            },
            { code: "p-dd30d", label: "30天订单", value: "-" },
            { code: "p-mjs180d", label: "180天买家", value: "-" },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 47.0,
              value: "47",
            },
            { code: "p-sx30d", label: "近30天上新", value: "-" },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 24.0,
              value: "24",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "福建省厦门市" },
          ],
          title: "瑜伽裤运动高弹打底裤跨境高腰收腹无痕新款",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "✨综合服务分3.3，表现良好",
          ],
          coreAttributes: [
            {
              label: "颜色",
              value:
                "浓缩咖啡Espresso coffee,海军蓝Navy blue,石墨灰Graphite Grey,黑色Black,安可拉红Encore red",
            },
            { label: "功能", value: "加绒保暖" },
            { label: "面料", value: "晓星" },
            { label: "尺码", value: "4/S,6/M,8/L,10/XL" },
            { label: "下装款式", value: "紧身裤" },
            { label: "裤长", value: "长裤" },
            { label: "材质成分", value: "氨纶" },
            { label: "品牌", value: "weixian" },
            { label: "货号", value: "CK12" },
            { label: "上市年份季节", value: "全年" },
            { label: "适用对象", value: "瑜伽运动跑步健身户外爬山" },
          ],
          extraInfoDTO: { qwXl1y: 20 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01PkXCtX27tBjYqBIkO_!!2664557854-0-cib.jpg",
          itemId: "927810609505",
          itemPrice: "54.0",
          offerDetailUrl: "https://detail.1688.com/offer/927810609505.html",
          providerInfo: {
            companyName: "杭州一路发发跨境电子商务有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2219520734020d36d4",
            providerTags: [{ tagName: "诚信通1年", tagStyle: "GENERAL" }],
            userId: "2219520734020",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 86.0,
              value: "86%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 51.0,
              value: "51%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 3.3,
              value: "3.3",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 5533.0,
              value: "5533",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 16533.0,
              value: "16533",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 48001.0,
              value: "48001",
            },
            { code: "p-sx30d", label: "近30天上新", value: "-" },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 20.0,
              value: "20",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "浙江省金华市" },
          ],
          title: "加绒秋冬高腰设计瑜伽裤女收腹长裤打底保暖跑步运动紧身裤",
        },
        {
          aiAttentions: [
            "❗客服响应率0%，表现不佳",
            "❗综合服务分2.2，表现不佳",
          ],
          coreAttributes: [
            { label: "货源类别", value: "现货" },
            { label: "品牌", value: "其他" },
            { label: "货号", value: "lz1729465804955358001" },
            { label: "风格", value: "Athletic" },
            { label: "淘货类别", value: "其他" },
            { label: "款式", value: "长筒裤" },
            { label: "裤型", value: "直筒型" },
            { label: "裤长", value: "八分裤" },
            { label: "腰型", value: "高腰" },
            { label: "厚薄", value: "薄款" },
            { label: "图案", value: "其他" },
            { label: "误差范围", value: "其他" },
            { label: "适合季节", value: "春季" },
            { label: "适合人群", value: "青少年" },
            { label: "上市年份/季节", value: "2024年冬季" },
            { label: "面料名称", value: "竹纤维" },
            { label: "主面料成分", value: "兔毛" },
            { label: "主面料成分的含量", value: "其他" },
            { label: "工艺", value: "其他" },
            { label: "款式细节", value: "其他" },
            { label: "弹力", value: "高弹" },
            { label: "面料", value: "其他" },
            {
              label: "颜色",
              value: "Black,Deep Navy,Desert Shadows,Elemental Blue,Merlot",
            },
            {
              label: "尺码",
              value: "XX-Small,X-Small,Small,Medium,Large,X-Large,XXL/1X",
            },
            {
              label: "主要下游平台",
              value: "ebay,亚马逊,wish,速卖通,独立站,LAZADA,其他",
            },
            {
              label: "主要销售地区",
              value: "非洲,欧洲,南美,东南亚,北美,东北亚,中东,其他",
            },
            { label: "是否跨境出口专供货源", value: "是" },
            { label: "类别", value: "其他" },
            { label: "原创设计货源", value: "否" },
            { label: "有无质检报告", value: "否" },
            { label: "质检报告编号", value: "其他" },
            { label: "材质功能", value: "其他" },
            { label: "适用年龄段", value: "成人" },
            { label: "适用性别", value: "男" },
            { label: "产品类别", value: "休闲裤" },
          ],
          extraInfoDTO: {},
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01hx6Slu2Dz2XTws7Df_!!2220160348679-0-cib.jpg",
          itemId: "965858487408",
          itemPrice: "93.5",
          offerDetailUrl: "https://detail.1688.com/offer/965858487408.html",
          providerInfo: {
            companyName: "杭州建德玮琛贸易商行(个体工商户)",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2220160348679885c5",
            providerTags: [{ tagName: "诚信通1年", tagStyle: "GENERAL" }],
            userId: "2220160348679",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 1.0,
              value: "1%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 40.0,
              value: "40%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 2.2,
              value: "2.2",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 63.0,
              value: "63",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 161.0,
              value: "161",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 3460.0,
              value: "3460",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 468.0,
              value: "468",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [{ code: "o-xl", label: "近一年销量", value: "<10" }],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "浙江省温州市" },
          ],
          title: "代发跨境新款速卖通Women's High Waisted Legging",
        },
        {
          aiAttentions: [
            "❗客服响应率41%，表现不佳",
            "❗综合服务分2.6，表现不佳",
          ],
          coreAttributes: [
            { label: "货源类别", value: "现货" },
            { label: "品牌", value: "其他" },
            { label: "货号", value: "lz1729465804955358001" },
            { label: "风格", value: "Athletic" },
            { label: "淘货类别", value: "其他" },
            { label: "款式", value: "长筒裤" },
            { label: "裤型", value: "直筒型" },
            { label: "裤长", value: "八分裤" },
            { label: "腰型", value: "高腰" },
            { label: "厚薄", value: "薄款" },
            { label: "图案", value: "其他" },
            { label: "误差范围", value: "其他" },
            { label: "适合季节", value: "春季" },
            { label: "适合人群", value: "青少年" },
            { label: "上市年份/季节", value: "2024年冬季" },
            { label: "面料名称", value: "竹纤维" },
            { label: "主面料成分", value: "兔毛" },
            { label: "主面料成分的含量", value: "其他" },
            { label: "工艺", value: "其他" },
            { label: "款式细节", value: "其他" },
            { label: "弹力", value: "高弹" },
            { label: "面料", value: "其他" },
            {
              label: "颜色",
              value: "Black,Deep Navy,Desert Shadows,Elemental Blue,Merlot",
            },
            {
              label: "尺码",
              value: "XX-Small,X-Small,Small,Medium,Large,X-Large,XXL/1X",
            },
            {
              label: "主要下游平台",
              value: "ebay,亚马逊,wish,速卖通,独立站,LAZADA,其他",
            },
            {
              label: "主要销售地区",
              value: "非洲,欧洲,南美,东南亚,北美,东北亚,中东,其他",
            },
            { label: "是否跨境出口专供货源", value: "是" },
            { label: "类别", value: "其他" },
            { label: "原创设计货源", value: "否" },
            { label: "有无质检报告", value: "否" },
            { label: "质检报告编号", value: "其他" },
            { label: "材质功能", value: "其他" },
            { label: "适用年龄段", value: "成人" },
            { label: "适用性别", value: "男" },
            { label: "产品类别", value: "休闲裤" },
          ],
          extraInfoDTO: {},
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01NjoADj1sZILJ3u2mU_!!2220255655780-0-cib.jpg",
          itemId: "965774827911",
          itemPrice: "93.5",
          offerDetailUrl: "https://detail.1688.com/offer/965774827911.html",
          providerInfo: {
            companyName: "杭州建德梓森贸易商行（个体工商户）",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2220255655780bc003",
            providerTags: [{ tagName: "诚信通1年", tagStyle: "GENERAL" }],
            userId: "2220255655780",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 5.0,
              value: "5%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 41.0,
              value: "41%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 31.0,
              value: "31%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 2.6,
              value: "2.6",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 78.0,
              value: "78",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 130.0,
              value: "130",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 3805.0,
              value: "3805",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 1197.0,
              value: "1197",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [{ code: "o-xl", label: "近一年销量", value: "<10" }],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "浙江省杭州市" },
          ],
          title: "代发跨境新款速卖通Women's High Waisted Legging",
        },
        {
          aiAttentions: [
            "❗客服响应率0%，表现较差",
            "❗综合服务分2.1，表现不佳",
          ],
          coreAttributes: [
            { label: "主面料成分", value: "氨纶" },
            { label: "腰型", value: "其他" },
            { label: "货号", value: "laz601099549312275" },
            {
              label: "颜色",
              value: "Light Blue,Green,Black,grey,Milky,Purple,Chocolate",
            },
            {
              label: "尺码",
              value: "Asian S,Asian M,Asian L,Asian XL,Asian XXL",
            },
            { label: "品牌", value: "其他" },
            { label: "上市年份/季节", value: "2025年春季" },
            { label: "主面料成分含量", value: "30%以下" },
            { label: "风格", value: "原宿风" },
            { label: "款式", value: "其他" },
            { label: "风格类型", value: "日韩休闲" },
            { label: "流行元素", value: "其他" },
            { label: "面料名称", value: "雪尼尔" },
            { label: "是否跨境货源", value: "否" },
            { label: "工艺", value: "其他" },
          ],
          extraInfoDTO: {},
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01jSrHem1vg74mwY2uA_!!2219159786201-0-cib.jpg",
          itemId: "952621479671",
          itemPrice: "61.2",
          offerDetailUrl: "https://detail.1688.com/offer/952621479671.html",
          providerInfo: {
            companyName: "太原高浪金属制品有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2219159786201655ce",
            providerTags: [
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通1年", tagStyle: "GENERAL" },
            ],
            userId: "2219159786201",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 2.0,
              value: "2%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 32.0,
              value: "32%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 2.1,
              value: "2.1",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 149.0,
              value: "149",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 343.0,
              value: "343",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 2992.0,
              value: "2992",
            },
            { code: "p-sx30d", label: "近30天上新", value: "-" },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [{ code: "o-xl", label: "近一年销量", value: "<10" }],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "浙江省杭州市" },
          ],
          title: "2025跨境新款欧美高腰高腰瑜伽裤特点：合身高腰瑜伽裤",
        },
      ],
    },
    requestIntention: "AUTO",
    selectProviderRequestDTO: {
      intention: "AUTO",
      query: "找图上瑜伽裤，要黑色的",
      searchImageUrl:
        "https://cbu01.alicdn.com/img/ibank/O1CN011DeMsH1OHUUqXSGa3_!!4611686018427381392-0-overseas_pic.jpg",
      sessionId: "find_provider_877e19f4df314865a21f5cdf5351500c",
      taskId: "b4ac1c6ac5bb4070859edb7b8b3c9fc4",
      userModel: {
        loginId: "%E6%88%91%E6%98%AF%E9%A6%99%E9%A6%99%E5%91%80hh",
        timestamp: 1763649831972,
        userId: 2862546763,
      },
    },
  },
  reportSummary: "找商结果",
  saveToHistory: true,
  sessionId: "find_provider_877e19f4df314865a21f5cdf5351500c",
  taskId: "b4ac1c6ac5bb4070859edb7b8b3c9fc4",
  timestamp: 1763664519745,
  title: "找商结果",
};
