export default {
  cardId: "569eb14c5fb2440ab8c95829e46c1cb4",
  cardSubType: "SELECT_PROVIDER_BY_OFFER_CARD",
  cardType: "REPORT_CARD",
  eventType: "DATA_DISPLAY",
  imageUrl:
    "https://cbu01.alicdn.com/img/ibank/O1CN01bbF34N1WljZlw1rNF_!!4611686018427382541-0-overseas_pic.jpg",
  rawData: {
    offerInfo: {
      aiRequirementAnalysis: { isDisplay: false },
      offerList: [
        {
          aiAttentions: [
            "✨近30天上新159，全场最高",
            "✨30天订单2314，全场最高",
          ],
          coreAttributes: [
            { label: "风格", value: "时尚OL" },
            { label: "材质", value: "水晶" },
            { label: "品牌", value: "涵杰" },
            { label: "生产编号", value: "-" },
            { label: "销售序列号", value: "-" },
            { label: "种类", value: "手链" },
            { label: "样式", value: "女式" },
            { label: "造型", value: "几何型" },
            { label: "适用送礼场合", value: "旅游纪念" },
            { label: "加印LOGO", value: "可以" },
            { label: "加工定制", value: "是" },
            { label: "货号", value: "C437033049" },
            { label: "产地", value: "连云港" },
            { label: "镶嵌材质", value: "咨询" },
            {
              label: "主要下游平台",
              value:
                "淘宝,京东,ebay,PDD,亚马逊,wish,快手,LINIO,SHEIN,速卖通,天猫,独立站,LAZADA,拼多多,shopee,抖音,垂类电商,其他",
            },
            { label: "颜色", value: "C437芙蓉粉水晶原创手链" },
            { label: "有可授权的自有品牌", value: "是" },
            { label: "是否跨境出口专供货源", value: "是" },
            { label: "流行元素", value: "几何" },
            { label: "上市年份/季节", value: "2025年春季" },
            { label: "风格分类", value: "时尚通勤" },
            { label: "产品类别", value: "手饰" },
          ],
          extraInfoDTO: { xl1y: 8 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01tjGwwb22y9xp2fRZh_!!2256127188-0-cib.jpg",
          itemId: "918449518314",
          itemPrice: "52.9",
          offerDetailUrl: "https://detail.1688.com/offer/918449518314.html",
          providerInfo: {
            companyName: "东海县涵杰水晶制品有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2256127188",
            providerTags: [
              { tagName: "超级工厂", tagStyle: "SUPER_FACTORY" },
              { tagName: "实力商家", tagStyle: "POWER_FACTORY" },
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通12年", tagStyle: "GENERAL" },
            ],
            userId: "2256127188",
          },
          providerKjCustomTags: [
            "Logo定制",
            "包工包料",
            "包装定制",
            "无痕发货",
            "来图加工",
            "来样加工",
            "清加工",
            "贴标服务",
          ],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 99.0,
              value: "99%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 57.0,
              value: "57%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 4.0,
              value: "4.0",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 2314.0,
              value: "2314",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 7573.0,
              value: "7573",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 2555.0,
              value: "2555",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 159.0,
              value: "159",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年销量",
              originValue: 8.0,
              value: "<10",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "江苏省连云港市" },
          ],
          title: "定制天然水晶芙蓉粉水晶原创手链时尚大颗粒圆珠桃粉色女款手串",
        },
        {
          aiAttentions: [
            "✨综合服务分4.5，全场最佳",
            "✨品质退款率0%，表现优秀",
          ],
          coreAttributes: [
            { label: "材质", value: "粉水晶" },
            { label: "处理工艺", value: "抛光" },
            { label: "品牌", value: "无" },
            { label: "样式", value: "女式" },
            { label: "造型", value: "几何型" },
            { label: "适用送礼场合", value: "旅游纪念" },
            { label: "货号", value: "2023050160" },
            { label: "产地", value: "汕尾" },
            {
              label: "主要下游平台",
              value:
                "淘宝,京东,ebay,PDD,亚马逊,wish,快手,LINIO,SHEIN,速卖通,天猫,独立站,LAZADA,拼多多,shopee,抖音,垂类电商,其他",
            },
            { label: "有可授权的自有品牌", value: "否" },
            { label: "是否跨境出口专供货源", value: "是" },
            { label: "流行元素", value: "无" },
            { label: "上市年份/季节", value: "2023年春季" },
            { label: "风格", value: "百搭" },
            { label: "风格分类", value: "时尚通勤" },
            { label: "产品类别", value: "手饰" },
            {
              label: "主要销售地区",
              value: "非洲,欧洲,南美,东南亚,北美,东北亚,中东,其他",
            },
            { label: "适用人群", value: "女式" },
            { label: "流行元素分类", value: "无" },
          ],
          extraInfoDTO: { qwXl1y: 407 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01G4iWgI1U1LysPgAIX_!!2207567712457-0-cib.jpg",
          itemId: "722475270613",
          itemPrice: "21.5",
          offerDetailUrl: "https://detail.1688.com/offer/722475270613.html",
          providerInfo: {
            companyName: "海丰县可塘镇金鹏泰珠宝行",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-22075677124575b0a9",
            providerTags: [{ tagName: "诚信通6年", tagStyle: "GENERAL" }],
            userId: "2207567712457",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 89.0,
              value: "89%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 39.0,
              value: "39%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 4.5,
              value: "4.5",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 29.0,
              value: "29",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 192.0,
              value: "192",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 389.0,
              value: "389",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 1.0,
              value: "1",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 407.0,
              value: "407",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "广东省汕尾市" },
          ],
          title: "厂家直销天然粉水晶手链时尚百搭粉水晶串珠DIY手串批发",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "❗客服响应率70%，表现不佳",
          ],
          coreAttributes: [
            { label: "材质", value: "粉晶" },
            { label: "处理工艺", value: "手工" },
            { label: "品牌", value: "帝凯" },
            { label: "样式", value: "女式" },
            { label: "造型", value: "其他" },
            { label: "适用送礼场合", value: "展销会" },
            { label: "货号", value: "A1349" },
            { label: "产地", value: "汕尾" },
            {
              label: "主要下游平台",
              value:
                "淘宝,京东,ebay,PDD,亚马逊,wish,快手,LINIO,SHEIN,速卖通,天猫,独立站,LAZADA,拼多多,shopee,抖音,垂类电商,其他",
            },
            { label: "颜色", value: "A1349" },
            { label: "有可授权的自有品牌", value: "否" },
            { label: "是否跨境出口专供货源", value: "否" },
            { label: "流行元素", value: "无" },
            { label: "上市年份/季节", value: "2023年春季" },
            { label: "风格", value: "原创设计" },
            { label: "风格分类", value: "原创设计" },
            { label: "产品类别", value: "手饰" },
            { label: "适用人群", value: "女式" },
            { label: "流行元素分类", value: "无" },
          ],
          extraInfoDTO: { qwXl1y: 201, xl1y: 26 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01a7AD8Q1nnss8Y44uz_!!1105525135-0-cib.jpg",
          itemId: "954715148872",
          itemPrice: "47.0",
          offerDetailUrl: "https://detail.1688.com/offer/954715148872.html",
          providerInfo: {
            companyName: "海丰县可塘镇帝凯宝石厂",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=dikaik1",
            providerTags: [
              { tagName: "实力商家", tagStyle: "POWER_FACTORY" },
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通13年", tagStyle: "GENERAL" },
            ],
            userId: "1105525135",
          },
          providerKjCustomTags: ["包工包料", "来样加工", "清加工"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 70.0,
              value: "70%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 72.0,
              value: "72%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 3.5,
              value: "3.5",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 447.0,
              value: "447",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 1619.0,
              value: "1619",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 1549.0,
              value: "1549",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 105.0,
              value: "105",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 3.0,
              value: "3件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 201.0,
              value: "201",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "广东省汕尾市" },
          ],
          title: "粉水晶手链饰品 手工圆珠批发 天然水晶手串爆款饰品 水晶手链diy",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "❗客服响应率70%，表现较差",
          ],
          coreAttributes: [
            { label: "材质", value: "粉晶" },
            { label: "处理工艺", value: "手工" },
            { label: "品牌", value: "帝凯" },
            { label: "样式", value: "女式" },
            { label: "造型", value: "其他" },
            { label: "适用送礼场合", value: "展销会" },
            { label: "货号", value: "A1231" },
            { label: "产地", value: "汕尾" },
            {
              label: "主要下游平台",
              value:
                "淘宝,京东,ebay,PDD,亚马逊,wish,快手,LINIO,SHEIN,速卖通,天猫,独立站,LAZADA,拼多多,shopee,抖音,垂类电商,其他",
            },
            { label: "颜色", value: "A1231" },
            { label: "有可授权的自有品牌", value: "否" },
            { label: "是否跨境出口专供货源", value: "否" },
            { label: "流行元素", value: "无" },
            { label: "上市年份/季节", value: "2023年春季" },
            { label: "风格", value: "原创设计" },
            { label: "风格分类", value: "原创设计" },
            { label: "产品类别", value: "手饰" },
            { label: "适用人群", value: "女式" },
            { label: "流行元素分类", value: "无" },
          ],
          extraInfoDTO: { qwXl1y: 67, xl1y: 63 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01oTHSKV1nnss4uJFCf_!!1105525135-0-cib.jpg",
          itemId: "953704756575",
          itemPrice: "37.0",
          offerDetailUrl: "https://detail.1688.com/offer/953704756575.html",
          providerInfo: {
            companyName: "海丰县可塘镇帝凯宝石厂",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=dikaik1",
            providerTags: [
              { tagName: "实力商家", tagStyle: "POWER_FACTORY" },
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通13年", tagStyle: "GENERAL" },
            ],
            userId: "1105525135",
          },
          providerKjCustomTags: ["包工包料", "来样加工", "清加工"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 70.0,
              value: "70%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 72.0,
              value: "72%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 3.5,
              value: "3.5",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 447.0,
              value: "447",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 1619.0,
              value: "1619",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 1549.0,
              value: "1549",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 105.0,
              value: "105",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 3.0,
              value: "3件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 67.0,
              value: "67",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "广东省汕尾市" },
          ],
          title: "粉水晶手链diy 手工圆珠批发 天然水晶手串爆款饰品 珠宝手串手链",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "✨客服响应率96%，响应及时",
          ],
          coreAttributes: [
            { label: "材质", value: "水晶" },
            { label: "风格", value: "民族风" },
            { label: "品牌", value: "亦蝶" },
            { label: "样式", value: "男女通用" },
            { label: "造型", value: "圆珠" },
            { label: "处理工艺", value: "抛光" },
            { label: "水晶种类", value: "粉晶" },
            { label: "销售序列号", value: "DY4728" },
            { label: "生产编号", value: "DY4728" },
            { label: "产地", value: "金华" },
            { label: "货号", value: "DY4728" },
            { label: "加印LOGO", value: "可以" },
            {
              label: "适用送礼场合",
              value: "婚庆,生日,旅游纪念,节日,乔迁,展销会",
            },
            { label: "包装", value: "独立包装" },
            { label: "加工定制", value: "是" },
            { label: "镶嵌材质", value: "未镶嵌" },
            {
              label: "主要下游平台",
              value: "淘宝,快手,天猫,拼多多,抖音,垂类电商",
            },
            { label: "纯度", value: "6mm,8mm,10mm" },
            { label: "是否跨境出口专供货源", value: "否" },
            { label: "上市年份/季节", value: "2025夏季" },
            { label: "流行元素", value: "民族风" },
            { label: "产品类别", value: "手饰" },
            { label: "种类", value: "手串" },
          ],
          extraInfoDTO: { qwXl1y: 45 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01qeZaz31WN090ZE7Y9_!!2677572775-0-cib.jpg",
          itemId: "940846582668",
          itemPrice: "18.0",
          offerDetailUrl: "https://detail.1688.com/offer/940846582668.html",
          providerInfo: {
            companyName: "义乌市亦蝶饰品有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2677572775da1a8",
            providerTags: [
              { tagName: "实力商家", tagStyle: "POWER_FACTORY" },
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通11年", tagStyle: "GENERAL" },
            ],
            userId: "2677572775",
          },
          providerKjCustomTags: [
            "包工包料",
            "来图加工",
            "来样加工",
            "贴标服务",
            "轻加工",
          ],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 96.0,
              value: "96%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 66.0,
              value: "66%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 3.7,
              value: "3.7",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 1142.0,
              value: "1142",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 4406.0,
              value: "4406",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 1215.0,
              value: "1215",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 14.0,
              value: "14",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 45.0,
              value: "45",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "浙江省金华市" },
          ],
          title: "定制水晶手串小饰品串珠手链女批发素圈水晶天然高级紫粉晶手串",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "❗客服响应率70%，表现不佳",
          ],
          coreAttributes: [
            { label: "材质", value: "粉晶" },
            { label: "处理工艺", value: "手工" },
            { label: "品牌", value: "帝凯" },
            { label: "样式", value: "女式" },
            { label: "造型", value: "其他" },
            { label: "适用送礼场合", value: "展销会" },
            { label: "货号", value: "609" },
            { label: "产地", value: "汕尾" },
            {
              label: "主要下游平台",
              value:
                "淘宝,京东,ebay,PDD,亚马逊,wish,快手,LINIO,SHEIN,速卖通,天猫,独立站,LAZADA,拼多多,shopee,抖音,垂类电商,其他",
            },
            { label: "颜色", value: "A609" },
            { label: "有可授权的自有品牌", value: "否" },
            { label: "是否跨境出口专供货源", value: "否" },
            { label: "流行元素", value: "无" },
            { label: "上市年份/季节", value: "2023年春季" },
            { label: "风格", value: "原创设计" },
            { label: "风格分类", value: "原创设计" },
            { label: "产品类别", value: "手饰" },
            { label: "适用人群", value: "女式" },
            { label: "流行元素分类", value: "无" },
          ],
          extraInfoDTO: { qwXl1y: 30, xl1y: 12 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01umLw941nnspcWEKtj_!!1105525135-0-cib.jpg",
          itemId: "826079651662",
          itemPrice: "47.0",
          offerDetailUrl: "https://detail.1688.com/offer/826079651662.html",
          providerInfo: {
            companyName: "海丰县可塘镇帝凯宝石厂",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=dikaik1",
            providerTags: [
              { tagName: "实力商家", tagStyle: "POWER_FACTORY" },
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通13年", tagStyle: "GENERAL" },
            ],
            userId: "1105525135",
          },
          providerKjCustomTags: ["包工包料", "来样加工", "清加工"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 70.0,
              value: "70%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 72.0,
              value: "72%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 3.5,
              value: "3.5",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 447.0,
              value: "447",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 1619.0,
              value: "1619",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 1549.0,
              value: "1549",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 105.0,
              value: "105",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 3.0,
              value: "3件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 30.0,
              value: "30",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "广东省汕尾市" },
          ],
          title: "粉水晶手链diy 手工圆珠批发 天然水晶手串爆款饰品 珠宝手串批发",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "❗客服响应率70%，表现不佳",
          ],
          coreAttributes: [
            { label: "材质", value: "粉晶" },
            { label: "处理工艺", value: "手工" },
            { label: "品牌", value: "帝凯" },
            { label: "样式", value: "女式" },
            { label: "造型", value: "其他" },
            { label: "适用送礼场合", value: "展销会" },
            { label: "货号", value: "A1215" },
            { label: "产地", value: "汕尾" },
            {
              label: "主要下游平台",
              value:
                "淘宝,京东,ebay,PDD,亚马逊,wish,快手,LINIO,SHEIN,速卖通,天猫,独立站,LAZADA,拼多多,shopee,抖音,垂类电商,其他",
            },
            { label: "颜色", value: "A1215" },
            { label: "有可授权的自有品牌", value: "否" },
            { label: "是否跨境出口专供货源", value: "否" },
            { label: "流行元素", value: "无" },
            { label: "上市年份/季节", value: "2023年春季" },
            { label: "风格", value: "原创设计" },
            { label: "风格分类", value: "原创设计" },
            { label: "产品类别", value: "手饰" },
            { label: "适用人群", value: "女式" },
            { label: "流行元素分类", value: "无" },
          ],
          extraInfoDTO: { xl1y: 102 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01R4layR1nnss6DFMu6_!!1105525135-0-cib.jpg",
          itemId: "953724924308",
          itemPrice: "37.0",
          offerDetailUrl: "https://detail.1688.com/offer/953724924308.html",
          providerInfo: {
            companyName: "海丰县可塘镇帝凯宝石厂",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=dikaik1",
            providerTags: [
              { tagName: "实力商家", tagStyle: "POWER_FACTORY" },
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通13年", tagStyle: "GENERAL" },
            ],
            userId: "1105525135",
          },
          providerKjCustomTags: ["包工包料", "来样加工", "清加工"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 70.0,
              value: "70%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 72.0,
              value: "72%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 3.5,
              value: "3.5",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 447.0,
              value: "447",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 1619.0,
              value: "1619",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 1549.0,
              value: "1549",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 105.0,
              value: "105",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 3.0,
              value: "3件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年销量",
              originValue: 102.0,
              value: "102",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "广东省汕尾市" },
          ],
          title: "粉水晶手链diy 手工圆珠批发 天然水晶手串爆款饰品 珠宝手链饰品",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "❗客服响应率70%，表现不佳",
          ],
          coreAttributes: [
            { label: "材质", value: "粉水晶" },
            { label: "处理工艺", value: "手工" },
            { label: "品牌", value: "帝凯" },
            { label: "样式", value: "女式" },
            { label: "造型", value: "其他" },
            { label: "适用送礼场合", value: "展销会" },
            { label: "货号", value: "456" },
            { label: "产地", value: "汕尾" },
            {
              label: "主要下游平台",
              value:
                "淘宝,京东,ebay,PDD,亚马逊,wish,快手,LINIO,SHEIN,速卖通,天猫,独立站,LAZADA,拼多多,shopee,抖音,垂类电商,其他",
            },
            { label: "颜色", value: "A456" },
            { label: "有可授权的自有品牌", value: "否" },
            { label: "是否跨境出口专供货源", value: "否" },
            { label: "流行元素", value: "无" },
            { label: "上市年份/季节", value: "2023年春季" },
            { label: "风格", value: "原创设计" },
            { label: "风格分类", value: "原创设计" },
            { label: "产品类别", value: "手饰" },
            { label: "适用人群", value: "女式" },
            { label: "流行元素分类", value: "无" },
          ],
          extraInfoDTO: { xl1y: 70 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN011b13Iz1nnslcJDsVo_!!1105525135-0-cib.jpg",
          itemId: "814627030777",
          itemPrice: "37.0",
          offerDetailUrl: "https://detail.1688.com/offer/814627030777.html",
          providerInfo: {
            companyName: "海丰县可塘镇帝凯宝石厂",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=dikaik1",
            providerTags: [
              { tagName: "实力商家", tagStyle: "POWER_FACTORY" },
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通13年", tagStyle: "GENERAL" },
            ],
            userId: "1105525135",
          },
          providerKjCustomTags: ["包工包料", "来样加工", "清加工"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 70.0,
              value: "70%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 72.0,
              value: "72%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 3.5,
              value: "3.5",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 447.0,
              value: "447",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 1619.0,
              value: "1619",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 1549.0,
              value: "1549",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 105.0,
              value: "105",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 3.0,
              value: "3件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年销量",
              originValue: 70.0,
              value: "70",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "广东省汕尾市" },
          ],
          title: "粉水晶手链diy 手工圆珠批发 珠宝首饰批发 天然水晶手串爆款饰品",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "✨客服响应率96%，表现优秀",
          ],
          coreAttributes: [
            { label: "材质", value: "水晶" },
            { label: "风格", value: "民族风" },
            { label: "品牌", value: "亦蝶" },
            { label: "样式", value: "男女通用" },
            { label: "造型", value: "圆珠" },
            { label: "处理工艺", value: "抛光" },
            { label: "水晶种类", value: "粉晶" },
            { label: "销售序列号", value: "DY4729" },
            { label: "生产编号", value: "DY4729" },
            { label: "产地", value: "金华" },
            { label: "货号", value: "DY4729" },
            { label: "加印LOGO", value: "可以" },
            {
              label: "适用送礼场合",
              value: "婚庆,生日,旅游纪念,节日,乔迁,展销会",
            },
            { label: "包装", value: "独立包装" },
            { label: "加工定制", value: "是" },
            { label: "镶嵌材质", value: "未镶嵌" },
            { label: "品相", value: "精品(十品)" },
            {
              label: "主要下游平台",
              value: "淘宝,快手,天猫,拼多多,抖音,垂类电商",
            },
            {
              label: "颜色",
              value: "款式一,款式二,款式三,款式四,款式五,款式六",
            },
            { label: "是否跨境出口专供货源", value: "否" },
            { label: "上市年份/季节", value: "2025夏季" },
            { label: "流行元素", value: "民族风" },
            { label: "产品类别", value: "手饰" },
            { label: "种类", value: "手串" },
          ],
          extraInfoDTO: { xl1y: 1 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01Yqngg71WN08zcBKfZ_!!2677572775-0-cib.jpg",
          itemId: "940418959574",
          itemPrice: "24.0",
          offerDetailUrl: "https://detail.1688.com/offer/940418959574.html",
          providerInfo: {
            companyName: "义乌市亦蝶饰品有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2677572775da1a8",
            providerTags: [
              { tagName: "实力商家", tagStyle: "POWER_FACTORY" },
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通11年", tagStyle: "GENERAL" },
            ],
            userId: "2677572775",
          },
          providerKjCustomTags: [
            "包工包料",
            "来图加工",
            "来样加工",
            "贴标服务",
            "轻加工",
          ],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 96.0,
              value: "96%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 66.0,
              value: "66%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 3.7,
              value: "3.7",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 1142.0,
              value: "1142",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 4406.0,
              value: "4406",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 1215.0,
              value: "1215",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 14.0,
              value: "14",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年销量",
              originValue: 1.0,
              value: "<10",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "浙江省金华市" },
          ],
          title: "定制天然紫粉晶手串水晶天然高货原创个性新中式手串珠手链高级感",
        },
        {
          aiAttentions: [
            "✨近一年全网销量7.6万+，热销榜首",
            "✨商品价格¥0.65，超低价",
          ],
          coreAttributes: [
            { label: "材质", value: "合金" },
            { label: "处理工艺", value: "手工" },
            { label: "品牌", value: "无" },
            { label: "样式", value: "女式" },
            { label: "造型", value: "其他" },
            { label: "适用送礼场合", value: "员工福利" },
            { label: "货号", value: "1" },
            { label: "产地", value: "义乌" },
            { label: "主要下游平台", value: "淘宝,拼多多" },
            {
              label: "颜色",
              value:
                "S077-可爱五角星多色手串#SZ609,S077-奶油海星多色手串#SZ610,S143-冰激凌炭烤猫爪手串#SZ808,S008-灰月光【仿猫眼石】#SZ112,S008-黑曜石【仿猫眼石】#SZ116,S008-海蓝宝【仿猫眼石】#SZ115,S008-紫水晶【仿猫眼石】#SZ113,S008-草莓晶【仿猫眼石】#SZ114,S014-蝴蝶仿猫眼石手串#SZ157,S014-草绿蝴蝶仿猫眼石手串#SZ266,S014-绿色蝴蝶仿猫眼石手链#SZ269,S014-红色蝴蝶仿猫眼石手链#SZ268,粉色蝴蝶仿猫眼石手链#SZ267,S012-玉碎蝴蝶手链【蓝色】#SZ144,S012-玉碎蝴蝶手链【粉色】#SZ145,S012-玉碎蝴蝶手链【绿色】#SZ143,S012-玉碎蝴蝶手链【浅蓝】#SZ272,S012-玉碎蝴蝶手链【黑色】#SZ273,S012-玉碎蝴蝶手链【玫粉色】#SZ274,S012-玉碎蝴蝶手链【蓝黄】#SZ271,S012-玉碎蝴蝶手链【深蓝】#SZ270,S018-粉色蝴蝶结铃兰花手串#SZ189,S018-绿色蝴蝶结铃兰花手串#SZ188,S018-蓝色蝴蝶结铃兰花手串#SZ187,S016-KT猫仿猫眼石手链SZ167,S016-KT猫仿猫眼石手链（紫色）#SZ362,S016-KT猫仿猫眼石手链（浅绿）#SZ363,S016-KT猫仿猫眼石手链（蓝色）#SZ360,S016-KT猫仿猫眼石手链（粉色）#SZ361,S165-樱花碎珠手链#SZ450,S151-多彩天然石莲蓬手串#SZ447,S065-仿猫眼绿色福牌手串#SZ525,S158-星星猫眼石手串#SZ147,S137-仿猫眼紫色星星手链#SZ526,S065-仿猫眼灰色福牌手串#SZ523,S065-仿猫眼紫色福牌手串#SZ527,S138-仿猫眼紫色蝴蝶结手链#SZ524,S008-青草绿铃铛手链#SZ210,S070-12MM手串【冰透粉】玻璃材质#SZ559,S070-12MM手串【冰透白】玻璃材质#SZ558,S070-12MM手串【冰透蓝】玻璃材质#SZ557,S070-12MM手串【冰透黄】玻璃材质#SZ556,【12m随机颜色】玻璃手串一条,S301-12MM黑紫色冰裂手串#SZ1206,S301-12MM蓝紫色冰裂手串#SZ1207,S301-12MM浅紫色冰裂手串#SZ1208,S301-12MM蓝橙色冰裂手串#SZ1209,S009-银色开口手镯#SZ070,S071-【10mm小号冰透粉】玻璃#SZ563,S071-【10mm小号冰透黄】玻璃#SZ562,S071-【10mm小号冰透蓝】玻璃#SZ560,S071-【10mm小号冰透白】玻璃#SZ561,S071-【10mm小号粉黄色】玻璃#SZ570,S071-【10mm小号蓝红色】玻璃#SZ575,S071-【10mm小号黄蓝色】玻璃#SZ572,S071-【10mm小号黄白色】玻璃#SZ574,S071-【10mm小号蓝粉色】玻璃#SZ571,S071-【10mm小号蓝紫色】玻璃#SZ573,S072-渐变手串【星空绿】#SZ566,S072-渐变手串【星空紫】#SZ567,S072-渐变手串【星空粉】#SZ564,S072-渐变手串【星空蓝】#SZ565,S073-白玉红珠手链白长命锁#SZ569,S073-白玉绿珠手链绿长命锁#SZ568,S010-白色珠子玉兔手链#SZ119,S010-红色珠子玉兔手链SZ168,S067-猫爪【渐变蓝】手串#SZ541,S067-猫爪【渐变绿】手串#SZ542,S067-猫爪【渐变粉】手串#SZ544,S067-猫爪【渐变紫】手串#SZ543,S069-爆裂白吊珠手串#SZ550,S069-爆裂蓝吊珠手串#SZ551,S069-爆裂红吊珠手串#SZ552,S069-爆裂橘粉吊珠手串#SZ554,S069-爆裂绿吊珠手串#SZ555,S069-爆裂粉吊珠手串#SZ553,S015-玫红色清新小花手串#SZ162,S015-蓝色清新小花手串#SZ173,S015-黄色清新小花手串SZ175,S015-混彩色清新小花手串#SZ161,S015-大红色清新小花手串#SZ163,S015-粉色清新小花手串SZ174,S015-绿色清新小花手串#SZ172,S015-白色清新小花手串SZ177,S060-大红色雏菊手串#SZ533,S060-浅绿色雏菊手串#SZ532,S060-白色雏菊手串#SZ537,S060-蓝色串大红吊坠雏菊手串#SZ531,S060-粉色串珠大红色雏菊手串#SZ534,S060-紫色雏菊手串#SZ535,S060-蓝色雏菊手串#SZ536,S060-粉色雏菊手串#SZ538,S060-黄色雏菊手串#SZ539,S060-彩色雏菊手串#SZ540,S048-红枫叶东林玉串珠手链#SZ340,S048-金钱袋东林玉串珠手链#SZ341,S048-绿龙珠东林玉串珠手链#SZ342,S048-萤火虫东林玉串珠手链#SZ344,S048-白狐狸东林玉串珠手链#SZ343,S048-绿福袋东林玉串珠手链#SZ345,S048-白蝴蝶东林玉串珠手链#SZ346,S048-白平安扣东林玉串珠手链#SZ347,S048-红平安锁东林玉串珠手链#SZ348,S048-白平安锁东林玉串珠手链#SZ349,S048-绿平安扣东林玉串珠手链#SZ350,S048-红花生东林玉串珠手链#SZ353,S048-绿平安锁东林玉串珠手链#SZ352,S048-白花生东林玉串珠手链#SZ354,S048-绿四叶草东林玉串珠手链#SZ356,S048-绿花生东林玉串珠手链#SZ355,S047-红枫叶敦敦绿珠手串#SZ336,S047-绿貔貅敦敦绿珠手串#SZ335,S047-萤火虫敦敦绿珠手串#SZ332,S047-绿平安锁敦敦绿珠手串#SZ337,S047-绿蝴蝶敦敦绿珠手串#SZ334,S047-金钱袋敦敦绿珠手串#SZ333,S045-鸡蛋黄-玉碎仿陶瓷手链#SZ329,S045-柠檬绿-玉碎仿陶瓷手链#SZ328,S045-蓝紫相间-玉碎仿陶瓷手链#SZ327,S045-红绿渐变-玉碎仿陶瓷手链#SZ325,S045-大理石-玉碎仿陶瓷手链#SZ324,S045-地图色-玉碎仿陶瓷手链#SZ322,S045-黄蓝渐变-玉碎仿陶瓷手链#SZ321,S045-清新紫-玉碎仿陶瓷手链#SZ320,S045-水彩绿-玉碎仿陶瓷手链#SZ319,S045-桃花红-玉碎仿陶瓷手链#SZ323,S045-鲜花红-玉碎仿陶瓷手链#SZ318,S045-鲜橙黄-玉碎仿陶瓷手链#SZ316,S045-红黄相间-玉碎仿陶瓷手链#SZ317,S052-宝蓝色银河星星手链#SZ377,S048-仿和田玉四叶草绿手串#SZ465,S025-【绿色】郁金香手链#SZ215,S025-【粉色】郁金香手链#SZ214,S025-【蓝色】郁金香手链#SZ213,S025-【黄色】郁金香手链#SZ212,S025-【白色】郁金香手链#SZ211,S028-紫色金蝴蝶芝士奶盖手链#SZ225,S028-绿色金蝴蝶芝士奶盖手链#SZ222,S028-蓝色金蝴蝶芝士奶盖手链#SZ224,S028-粉色金蝴蝶芝士奶盖手链#SZ223,S020-白色人偶玉桂狗爆花手串#SZ529,S020-粉色库洛米混彩爆花手串#SZ430,S020-紫色猫飞碟爆花手串#SZ438,S020-蓝色皇冠库洛米飞碟爆花手串#SZ437,S020-蓝色猫猫爆花飞碟手链#SZ436,S020-黑色皇冠库洛米紫色爆花手串#SZ435,S020-橘粉星黛露爆花手串#SZ434,S020-粉色库洛米粉色爆花手串#SZ433,S020-长耳狗抱爱心混彩爆花手串#SZ432,S020-粉色美乐蒂混彩爆花手串#SZ429,S020-蓝色库洛米混彩爆花手串#SZ428,S020-长耳狗混彩爆花手串#SZ427,S020-蓝色美乐蒂混彩爆花手串#SZ426,S020-小黄狗混彩爆花手串#SZ425,S020-短耳朵玉桂狗混彩爆花手串#SZ424,S020-随机一条三丽鸥爆花手串#SZ090,S020-蓝色美乐蒂爆花手串#SZ085,S020-蓝色叮当猫爆花手串#SZ084,S020-蓝色长耳朵玉桂狗爆花手镯#SZ083,S020-粉色星黛露爆花手串#SZ082,S020-紫色美乐蒂爆花手串#SZ081,S020-草莓熊爆花手串#SZ080,S020-橘黄美乐蒂混彩爆花手串#SZ431,S050-金色猫咪粉色爆花手串#SZ373,S050-金色猫咪玫粉爆花手串#SZ372,S050-金色猫咪绿色爆花手串#SZ371,S030-湖蓝竹节串珍珠月亮兔手链#SZ231,S030-蓝色竹节串珍珠玉桂狗手链#SZ230,S030-粉黄竹节串珍珠月亮兔手链#SZ228,S030-绿色竹节串珍珠蓝美乐蒂手链#SZ232,S030-粉色竹节串珍珠粉库洛米手链#SZ229,S013-红紫蝴蝶吊坠珍珠爆花手串#SZ148,S013-深蓝蝴蝶吊坠珍珠爆花手串#SZ151,S013-浅蓝色蝴蝶吊坠珍珠爆花手串#SZ152,S013-蓝绿蝴蝶吊坠珍珠爆花手串#SZ153,S013-蓝色云朵兔子手串#SZ149,S013-粉色云朵兔子手串#SZ150,S055-黑色爆花蝴蝶串珠手链#SZ457,S055-蓝色爆花蝴蝶串珠手链#SZ456,S055-绿色爆花树叶串珠手链#SZ454,S024-爆花闪钻蝴蝶黑手链#SZ204,S024-爆花闪钻蝴蝶枚红手链#SZ205,S024-爆花闪钻蝴蝶浅紫手链#SZ206,S024-爆花闪钻蝴蝶蓝手链#SZ207,S024-爆花闪钻蝴蝶粉手链#SZ208,S024-爆花闪钻蝴蝶深紫手链#SZ209,S192-绿色方糖莲蓬手链#SZ582,S074-相扣手链绿珠#SZ577,S074-相扣手链红珠#SZ576,S195-草莓红福字玻璃手串#SZ142,S177-白珠月亮铃铛手链#SZ458,S185-白KT猫蝴蝶结手串#SZ399,S201-粉色魏枝手链#SZ463,S197-粉色桃花莲蓬手串#SZ366,S017-粉色铃兰花手串#SZ180,S017-蓝色铃兰花手串#SZ183,S017-紫色铃兰花手串#SZ182,S017-浅蓝色铃兰花手串#SZ184,S017-玫红铃兰花手串#SZ179,S017-白色铃兰花手串#SZ185,S017-黄色铃兰花手串#SZ178,S017-混彩铃兰花手串#SZ181,S017-墨绿色铃兰花手串#SZ186,S033-玻璃仿玉铃兰花手链--白色#SZ239,S033-玻璃仿玉铃兰花手链--紫白#SZ240,S033-玻璃仿玉铃兰花手链--紫绿#SZ241,S033-玻璃仿玉铃兰花手链--粉黄#SZ242,S033-玻璃仿玉铃兰花手链--粉白#SZ243,S033-玻璃仿玉铃兰花手链--粉蓝#SZ244,S033-玻璃仿玉铃兰花手链--橘白#SZ245,S033-玻璃仿玉铃兰花手链--混色#SZ246,S033-玻璃仿玉铃兰花手链--绿白#SZ247,S033-玻璃仿玉铃兰花手链--蓝白#SZ248,S044-蓝色渐变铃兰花手链#SZ314,S044-粉色渐变铃兰花手链#SZ313,S044-粉变绿渐变铃兰花手链#SZ312,S186-竹节铃兰花手链#SZ452,S187-竹节锦上添花手链#SZ449,S004-白色竹节福字红珠手链#SZ128,S004-绿色竹节福字红珠手链#SZ129,S004-黄色竹节福字红珠手链#SZ057,S004-粉色竹节福字红珠手链#SZ056,S056-蓝色贝壳叶平安扣手串#SZ473,S056-黄色贝壳叶平安扣手串#SZ466,S056-草莓红贝壳叶平安扣手串#SZ467,S056-白色贝壳叶平安扣手串#SZ468,S056-粉色贝壳叶平安扣手串#SZ469,S056-混彩贝壳叶平安扣手串#SZ470,S056-大红贝壳叶平安扣手串#SZ471,S056-紫色贝壳叶平安扣手串#SZ472,S219-粉色珠桃花手链#SZ461,S023-帕恰狗玻璃手串#SZ200,S023-KT猫玻璃手串#SZ203,S023-玉桂狗玻璃手串#SZ201,S063-天然红玛瑙好事花生手链#SZ517,S063-天然白玛瑙好事花生手链#SZ515,S063-仿天然绿玛瑙好事花生手链#SZ516,S062-黄紫猫算盘手串#SZ510,S062-可乐咖猫算盘手串#SZ512,S062-绿白猫算盘手串#SZ511,S062-蓝黄猫算盘手串#SZ513,S062-紫色猫算盘手串#SZ514,S212-白珠长命锁铃铛手链#SZ460,S169-深蓝流星手链#SZ528,S053-8MM白珠纳福朱砂手链#SZ410,S053-10MM仿朱砂福牌手串#SZ411,S053-海绵宝宝朱砂色手串#SZ404,S053-小猫朱砂色手串#SZ403,S053-朱砂色手镯#SZ406,S053-朱砂色醒狮手串#SZ405,S248-招财纳福 金粉KT猫朱砂手链#SZ509,S053-满福转运朱砂手链#SZ508,S053-6MM朱砂和田玉福牌#SZ507,S161-朱砂红招财纳福龙饺手链#SZ339,S179-红珠镶钻星月玻璃手串#SZ054,S179-白珠镶钻星月玻璃手串#SZ055,S023-三丽鸥玻璃手串3件装#SZ199,S004-灰色竹节福字红珠手链#SZ191",
            },
            { label: "有可授权的自有品牌", value: "否" },
            { label: "是否跨境出口专供货源", value: "否" },
            { label: "流行元素", value: "无" },
            { label: "上市年份/季节", value: "2024年夏季" },
            { label: "风格", value: "甜美" },
            { label: "风格分类", value: "清新甜美" },
            { label: "产品类别", value: "手饰" },
            { label: "适用人群", value: "女式" },
            { label: "流行元素分类", value: "无" },
          ],
          extraInfoDTO: { qwXl1y: 75760, xl1y: 36787 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01Gr9uO427SAIxBGBQA_!!2216011547795-0-cib.jpg",
          itemId: "817281769917",
          itemPrice: "0.65",
          offerDetailUrl: "https://detail.1688.com/offer/817281769917.html",
          providerInfo: {
            companyName: "义乌市妹林饰品商行",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-221601154779547f16",
            providerTags: [{ tagName: "诚信通3年", tagStyle: "GENERAL" }],
            userId: "2216011547795",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 87.0,
              value: "87%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 78.0,
              value: "78%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 3.9,
              value: "3.9",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 2065.0,
              value: "2065",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 7543.0,
              value: "7543",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 847.0,
              value: "847",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 70.0,
              value: "70",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 75760.0,
              value: "7.6万+",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            {
              code: "o-lyl",
              label: "发货履约率",
              originValue: 93.0,
              value: "93%",
            },
            {
              code: "o-lsl",
              label: "48小时揽收率",
              originValue: 93.0,
              value: "93%",
            },
            { code: "fhd", label: "发货地", value: "浙江省金华市" },
          ],
          title: "马卡龙彩色系陶瓷串珠手链女气质甜美可爱少女手串小众百搭手饰",
        },
        {
          aiAttentions: [
            "✨48小时揽收率100%，全场最佳",
            "✨发货履约率100%，全场最佳",
          ],
          coreAttributes: [
            { label: "材质", value: "水晶" },
            { label: "风格", value: "轻奢风" },
            { label: "品牌", value: "九玖子" },
            { label: "样式", value: "女式" },
            { label: "造型", value: "几何型" },
            { label: "处理工艺", value: "手工" },
            { label: "水晶种类", value: "粉晶" },
            { label: "销售序列号", value: "987766" },
            { label: "生产编号", value: "987789" },
            { label: "产地", value: "金华" },
            { label: "货号", value: "987677" },
            { label: "加印LOGO", value: "不可以" },
            { label: "适用送礼场合", value: "旅游纪念" },
            { label: "包装", value: "散装" },
            { label: "加工定制", value: "是" },
            { label: "镶嵌材质", value: "未镶嵌" },
            { label: "尺寸", value: "10mm" },
            { label: "颗数", value: "配件" },
            { label: "品相", value: "通货" },
            { label: "主要下游平台", value: "独立站,抖音" },
            { label: "上市年份/季节", value: "2025年春季" },
            { label: "产品类别", value: "手饰" },
            { label: "种类", value: "手串" },
          ],
          extraInfoDTO: { qwXl1y: 410, xl1y: 43 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01bY1BHa1nhTJLusxpr_!!2215559905121-0-cib.jpg",
          itemId: "928537310241",
          itemPrice: "18.9",
          offerDetailUrl: "https://detail.1688.com/offer/928537310241.html",
          providerInfo: {
            companyName: "汕头市龙湖区九玖子饰品商行",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2215559905121fa370",
            providerTags: [{ tagName: "诚信通3年", tagStyle: "GENERAL" }],
            userId: "2215559905121",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 86.0,
              value: "86%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 69.0,
              value: "69%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 4.1,
              value: "4.1",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 61.0,
              value: "61",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 257.0,
              value: "257",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 363.0,
              value: "363",
            },
            { code: "p-sx30d", label: "近30天上新", value: "-" },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 2.0,
              value: "2件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 410.0,
              value: "410",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            {
              code: "o-lyl",
              label: "发货履约率",
              originValue: 100.0,
              value: "100%",
            },
            {
              code: "o-lsl",
              label: "48小时揽收率",
              originValue: 100.0,
              value: "100%",
            },
            { code: "fhd", label: "发货地", value: "浙江省金华市" },
          ],
          title: "原创设计新款天然粉水晶手串手链甜美风小清新轻奢小众厂家直销",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "✨客服响应率98%，表现优秀",
          ],
          coreAttributes: [
            { label: "材质", value: "水晶" },
            { label: "处理工艺", value: "手工" },
            { label: "样式", value: "女式" },
            { label: "水晶种类", value: "粉晶" },
            { label: "造型", value: "其他" },
            { label: "适用送礼场合", value: "展销会" },
            { label: "货号", value: "hk066" },
            { label: "产地", value: "汕尾" },
            {
              label: "主要下游平台",
              value:
                "淘宝,京东,ebay,PDD,wish,快手,SHEIN,速卖通,天猫,LAZADA,拼多多,shopee,抖音",
            },
            { label: "颜色", value: "hk066" },
            { label: "有可授权的自有品牌", value: "否" },
            { label: "是否跨境出口专供货源", value: "是" },
            { label: "流行元素", value: "无" },
            { label: "上市年份/季节", value: "2025夏季" },
            { label: "风格", value: "原创设计" },
            { label: "风格分类", value: "原创设计" },
            { label: "产品类别", value: "手饰" },
            { label: "主要销售地区", value: "其他" },
            { label: "适用人群", value: "女式" },
            { label: "流行元素分类", value: "无" },
          ],
          extraInfoDTO: { xl1y: 4 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN018P38Dy2KPV7HLyPe0_!!2220253259549-0-cib.jpg",
          itemId: "968000808856",
          itemPrice: "57.0",
          offerDetailUrl: "https://detail.1688.com/offer/968000808856.html",
          providerInfo: {
            companyName: "广州市皇凯珠宝厂(个人独资)",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-22202532595493d183",
            providerTags: [
              { tagName: "实力商家", tagStyle: "POWER_FACTORY" },
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通1年", tagStyle: "GENERAL" },
            ],
            userId: "2220253259549",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 98.0,
              value: "98%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 71.0,
              value: "71%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 4.0,
              value: "4.0",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 273.0,
              value: "273",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 384.0,
              value: "384",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 437.0,
              value: "437",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 144.0,
              value: "144",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 2.0,
              value: "2件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年销量",
              originValue: 4.0,
              value: "<10",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "广东省汕尾市" },
          ],
          title: "天然粉水晶手串 轻奢高级感手链 粉晶手串闺蜜礼物 粉水晶手串diy",
        },
        {
          aiAttentions: [
            "✨客服响应率100%，全场最佳",
            "✨品质退款率0%，表现优秀",
          ],
          coreAttributes: [
            { label: "材质", value: "粉水晶手串" },
            { label: "货号", value: "111" },
            { label: "工艺", value: "打磨抛光" },
            { label: "是否进口", value: "否" },
            { label: "加工定制", value: "否" },
            { label: "品牌", value: "怡霖珠宝" },
            { label: "产品编号", value: "631" },
            { label: "类别", value: "手串" },
            { label: "材料来源", value: "天然" },
            { label: "净度", value: "VVS" },
            { label: "形状", value: "圆形" },
            { label: "摆挂形式", value: "挂饰" },
            { label: "包装", value: "PP袋独立包装" },
            { label: "是否专利货源", value: "否" },
            { label: "尺寸", value: "6mm" },
            {
              label: "主要下游平台",
              value: "ebay,亚马逊,wish,速卖通,独立站,LAZADA",
            },
            {
              label: "主要销售地区",
              value: "非洲,欧洲,南美,东南亚,北美,东北亚,中东",
            },
            { label: "有可授权的自有品牌", value: "否" },
            { label: "是否跨境出口专供货源", value: "是" },
            { label: "风格", value: "现代简约" },
            {
              label: "适用送礼场合",
              value: "满月,旅游纪念,毕业,乔迁,派对聚会,探病慰问",
            },
            {
              label: "适用送礼关系",
              value: "晚辈,情侣,夫妻,同事,朋友,长辈,孩子,同学,恩师",
            },
            {
              label: "适用节日",
              value:
                "圣诞节,情人节,春节,父亲节,母亲节,教师节,元旦,七夕,万圣节,复活节,国庆节,儿童节,妇女节",
            },
            { label: "是否属于礼品", value: "是，个人礼品" },
            { label: "是否IP授权", value: "否" },
            { label: "材质种类", value: "宝石" },
          ],
          extraInfoDTO: { qwXl1y: 95 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01j3O8ya1h0yZdC6oUs_!!2206786774216-0-cib.jpg",
          itemId: "676244238951",
          itemPrice: "68.0",
          offerDetailUrl: "https://detail.1688.com/offer/676244238951.html",
          providerInfo: {
            companyName: "海丰县城东怡霖珠宝加工厂",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-22067867742166c704",
            providerTags: [
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通7年", tagStyle: "GENERAL" },
            ],
            userId: "2206786774216",
          },
          providerKjCustomTags: ["包工包料", "来图加工", "来样加工", "轻加工"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 100.0,
              value: "100%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 28.0,
              value: "28%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 4.4,
              value: "4.4",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 6.0,
              value: "6",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 47.0,
              value: "47",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 300.0,
              value: "300",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 1.0,
              value: "1",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 2.0,
              value: "2件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 95.0,
              value: "95",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "广东省汕尾市" },
          ],
          title: "粉水晶手串粉水晶手串粉水晶晶体通透色泽光亮带桃花女友礼物批发",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "✨客服响应率95%，响应及时",
          ],
          coreAttributes: [
            { label: "材质", value: "水晶" },
            { label: "风格", value: "轻奢风" },
            { label: "品牌", value: "无" },
            { label: "样式", value: "女式" },
            { label: "造型", value: "星座" },
            { label: "处理工艺", value: "手工" },
            { label: "水晶种类", value: "粉晶" },
            { label: "产地", value: "连云港" },
            { label: "加印LOGO", value: "不可以" },
            {
              label: "适用送礼场合",
              value: "婚庆,生日,旅游纪念,周年庆典,开业典礼",
            },
            { label: "包装", value: "独立包装" },
            { label: "加工定制", value: "是" },
            { label: "镶嵌材质", value: "未镶嵌" },
            { label: "尺寸", value: "14mm" },
            { label: "颗数", value: "11" },
            { label: "品相", value: "精品(十品)" },
            { label: "主要下游平台", value: "wish,速卖通,LAZADA,抖音" },
            { label: "颜色", value: "14mm西柚粉水晶" },
            { label: "是否跨境出口专供货源", value: "否" },
            { label: "上市年份/季节", value: "2025年春季" },
            { label: "流行元素", value: "招桃花" },
            { label: "产品类别", value: "手饰" },
            { label: "种类", value: "手串" },
          ],
          extraInfoDTO: { qwXl1y: 21, xl1y: 9 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01dOM6Pr1YURnwqkKpV_!!2219352473062-0-cib.jpg",
          itemId: "916823275474",
          itemPrice: "128.0",
          offerDetailUrl: "https://detail.1688.com/offer/916823275474.html",
          providerInfo: {
            companyName: "东海县佰满恒珠宝加工厂（个体工商户）",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-22193524730626eaad",
            providerTags: [
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通1年", tagStyle: "GENERAL" },
            ],
            userId: "2219352473062",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 95.0,
              value: "95%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 52.0,
              value: "52%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 4.0,
              value: "4.0",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 55.0,
              value: "55",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 450.0,
              value: "450",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 401.0,
              value: "401",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 19.0,
              value: "19",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 21.0,
              value: "21",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "江苏省连云港市" },
          ],
          title: "天然粉水晶手串天然水晶手串女招桃花小众简约设计粉晶小红书时尚",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "✨综合服务分3.1，表现良好",
          ],
          coreAttributes: [
            { label: "产品类别", value: "手串" },
            { label: "水晶种类", value: "粉晶" },
            { label: "单珠直径", value: "8mm" },
            { label: "副石材质", value: "无副石" },
            { label: "配件材质", value: "无配件" },
            { label: "品牌", value: "蓝层阁" },
            { label: "产地", value: "乌拉圭" },
            { label: "包装", value: "独立包装" },
            { label: "上市年份/季节", value: "2022年春季" },
            { label: "风格", value: "中国风" },
            { label: "颜色", value: "粉晶手串" },
            { label: "尺码", value: "珠径8+mm" },
          ],
          extraInfoDTO: { qwXl1y: 2 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01eS4qNd27N7s5lH77R_!!2216434507784-0-cib.jpg",
          itemId: "747762105662",
          itemPrice: "22.0",
          offerDetailUrl: "https://detail.1688.com/offer/747762105662.html",
          providerInfo: {
            companyName: "镇平县黄菖蒲商贸有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-22164345077840e734",
            providerTags: [{ tagName: "诚信通3年", tagStyle: "GENERAL" }],
            userId: "2216434507784",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 82.0,
              value: "82%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 43.0,
              value: "43%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 3.1,
              value: "3.1",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 143.0,
              value: "143",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 673.0,
              value: "673",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 3830.0,
              value: "3830",
            },
            { code: "p-sx30d", label: "近30天上新", value: "-" },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 2.0,
              value: "2件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年全网销量",
              originValue: 2.0,
              value: "<10",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "河南省南阳市" },
          ],
          title: "粉晶手串",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "✨综合服务分3.1，表现良好",
          ],
          coreAttributes: [
            { label: "产品类别", value: "手串" },
            { label: "水晶种类", value: "粉晶" },
            { label: "单珠直径", value: "8mm" },
            { label: "副石材质", value: "无副石" },
            { label: "配件材质", value: "无配件" },
            { label: "品牌", value: "蓝层阁" },
            { label: "产地", value: "乌拉圭" },
            { label: "包装", value: "独立包装" },
            { label: "上市年份/季节", value: "2022年春季" },
            { label: "风格", value: "中国风" },
            { label: "颜色", value: "粉晶手串" },
            { label: "尺码", value: "珠径8+mm" },
          ],
          extraInfoDTO: {},
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01buJt8K27N7s6nwBpN_!!2216434507784-0-cib.jpg",
          itemId: "747618456305",
          itemPrice: "30.0",
          offerDetailUrl: "https://detail.1688.com/offer/747618456305.html",
          providerInfo: {
            companyName: "镇平县黄菖蒲商贸有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-22164345077840e734",
            providerTags: [{ tagName: "诚信通3年", tagStyle: "GENERAL" }],
            userId: "2216434507784",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 82.0,
              value: "82%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 43.0,
              value: "43%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 3.1,
              value: "3.1",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 143.0,
              value: "143",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 673.0,
              value: "673",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 3830.0,
              value: "3830",
            },
            { code: "p-sx30d", label: "近30天上新", value: "-" },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 2.0,
              value: "2件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [{ code: "o-xl", label: "近一年销量", value: "<10" }],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "河南省南阳市" },
          ],
          title: "粉晶手串",
        },
        {
          aiAttentions: [
            "✨48小时揽收率100%，表现优秀",
            "✨发货履约率100%，表现优秀",
          ],
          coreAttributes: [
            { label: "材质", value: "水晶" },
            { label: "样式", value: "女式" },
            { label: "产地", value: "金华" },
            { label: "镶嵌材质", value: "合金镶嵌人工宝石/半宝石" },
            { label: "上市年份/季节", value: "2022年夏季" },
            { label: "流行元素", value: "珍珠,水钻,田园,亮片" },
            { label: "产品类别", value: "手饰" },
            { label: "种类", value: "手串" },
          ],
          extraInfoDTO: { xl1y: 3 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN018fxyLY1MUebNrEVaY_!!2213981171438-0-cib.jpg",
          itemId: "931447268781",
          itemPrice: "14.0",
          offerDetailUrl: "https://detail.1688.com/offer/931447268781.html",
          providerInfo: {
            companyName: "广州市腾达珠宝饰品商行",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-22139811714386093f",
            providerTags: [{ tagName: "诚信通4年", tagStyle: "GENERAL" }],
            userId: "2213981171438",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 95.0,
              value: "95%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 51.0,
              value: "51%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 4.5,
              value: "4.5",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 257.0,
              value: "257",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 952.0,
              value: "952",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 1405.0,
              value: "1405",
            },
            {
              code: "p-sx30d",
              label: "近30天上新",
              originValue: 36.0,
              value: "36",
            },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 1.0,
              value: "1件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年销量",
              originValue: 3.0,
              value: "<10",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            {
              code: "o-lyl",
              label: "发货履约率",
              originValue: 100.0,
              value: "100%",
            },
            {
              code: "o-lsl",
              label: "48小时揽收率",
              originValue: 100.0,
              value: "100%",
            },
            { code: "fhd", label: "发货地", value: "河南省南阳市" },
          ],
          title: "粉水晶手串送女朋友闺蜜自留生日礼物",
        },
        {
          aiAttentions: [
            "❗综合服务分2.6，存在风险",
            "❗客服响应率75%，表现不佳",
          ],
          coreAttributes: [
            { label: "材质", value: "水晶" },
            { label: "处理工艺", value: "抛光" },
            { label: "品牌", value: "其他" },
            { label: "样式", value: "女式" },
            { label: "水晶种类", value: "草莓晶" },
            { label: "造型", value: "其他" },
            { label: "适用送礼场合", value: "其他" },
            { label: "货号", value: "AL673051776785" },
            { label: "产地", value: "广州" },
            {
              label: "主要下游平台",
              value:
                "淘宝,京东,ebay,PDD,亚马逊,wish,快手,LINIO,SHEIN,速卖通,天猫,独立站,LAZADA,拼多多,shopee,抖音,垂类电商,其他",
            },
            { label: "颜色", value: "草莓晶星星手链" },
            {
              label: "纯度",
              value: "13cm-14cm手围,14cm-15cm手围,16cm-17cm手围",
            },
            { label: "有可授权的自有品牌", value: "否" },
            { label: "是否跨境出口专供货源", value: "是" },
            { label: "流行元素", value: "八芒星" },
            { label: "上市年份/季节", value: "2022年夏季" },
            { label: "风格", value: "甜美" },
            { label: "风格分类", value: "清新甜美" },
            { label: "产品类别", value: "手饰" },
            {
              label: "主要销售地区",
              value: "非洲,欧洲,南美,东南亚,北美,东北亚,中东,其他",
            },
            { label: "适用人群", value: "女式" },
            { label: "流行元素分类", value: "形状/图案" },
          ],
          extraInfoDTO: {},
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01U8cTep1qbSig35re8_!!2214292975514-0-cib.jpg",
          itemId: "723868444698",
          itemPrice: "32.88",
          offerDetailUrl: "https://detail.1688.com/offer/723868444698.html",
          providerInfo: {
            companyName: "海丰县可塘镇宝旭珠宝行",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-22159142060965cd0b",
            providerTags: [{ tagName: "诚信通3年", tagStyle: "GENERAL" }],
            userId: "2215914206096",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 1.0,
              value: "1%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 75.0,
              value: "75%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 48.0,
              value: "48%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 2.6,
              value: "2.6",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 112.0,
              value: "112",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 764.0,
              value: "764",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 4945.0,
              value: "4945",
            },
            { code: "p-sx30d", label: "近30天上新", value: "-" },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 2.0,
              value: "2件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [{ code: "o-xl", label: "近一年销量", value: "<10" }],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "广东省汕尾市" },
          ],
          title: "ins小众原创设计天然水晶手串DIY草莓晶粉水晶手链厂家直批",
        },
        {
          aiAttentions: [
            "✨品质退款率0%，表现优秀",
            "❗客服响应率77%，表现不佳",
          ],
          coreAttributes: [
            { label: "材质", value: "水晶" },
            { label: "风格", value: "自然" },
            { label: "品牌", value: "无" },
            { label: "样式", value: "女式" },
            { label: "造型", value: "几何型" },
            { label: "处理工艺", value: "手工" },
            { label: "水晶种类", value: "粉晶" },
            { label: "销售序列号", value: "036" },
            { label: "生产编号", value: "036" },
            { label: "产地", value: "苏州" },
            { label: "货号", value: "036" },
            { label: "加印LOGO", value: "不可以" },
            { label: "适用送礼场合", value: "其他" },
            { label: "包装", value: "独立包装" },
            { label: "加工定制", value: "是" },
            { label: "镶嵌材质", value: "无" },
            { label: "尺寸", value: "10mm" },
            { label: "颗数", value: "18颗" },
            { label: "品相", value: "通货" },
            {
              label: "主要下游平台",
              value: "ebay,亚马逊,速卖通,独立站,LAZADA,其他",
            },
            { label: "颜色", value: "粉红色" },
            {
              label: "主要销售地区",
              value: "欧洲,南美,东南亚,北美,东北亚,中东,其他",
            },
            { label: "是否跨境出口专供货源", value: "是" },
            { label: "上市年份/季节", value: "2025年春季" },
            { label: "流行元素", value: "水晶" },
            { label: "产品类别", value: "手饰" },
            { label: "种类", value: "手串" },
          ],
          extraInfoDTO: { xl1y: 21 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01504sRr2HLQgYYn6jz_!!2218778499134-0-cib.jpg",
          itemId: "863292163452",
          itemPrice: "18.0",
          offerDetailUrl: "https://detail.1688.com/offer/863292163452.html",
          providerInfo: {
            companyName: "抚州市丙戊垚焱饰品有限公司",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2218778499134f4875",
            providerTags: [
              { tagName: "源头工厂", tagStyle: "SOURCE_FACTORY" },
              { tagName: "诚信通2年", tagStyle: "GENERAL" },
            ],
            userId: "2218778499134",
          },
          providerKjCustomTags: ["来图加工", "来样加工", "清加工"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 77.0,
              value: "77%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 69.0,
              value: "69%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 4.0,
              value: "4.0",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 4.0,
              value: "4",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 59.0,
              value: "59",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 103.0,
              value: "103",
            },
            { code: "p-sx30d", label: "近30天上新", value: "-" },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 2.0,
              value: "2件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年销量",
              originValue: 21.0,
              value: "21",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            { code: "o-lyl", label: "发货履约率", value: "-" },
            { code: "o-lsl", label: "48小时揽收率", value: "-" },
            { code: "fhd", label: "发货地", value: "江西省抚州市" },
          ],
          title: "天然粉水晶手串桃花手链Crystal bracelet",
        },
        {
          aiAttentions: [
            "✨48小时揽收率100%，表现优秀",
            "✨发货履约率100%，表现优秀",
          ],
          coreAttributes: [
            { label: "材质", value: "水晶" },
            { label: "风格", value: "自然" },
            { label: "品牌", value: "九玖子" },
            { label: "样式", value: "女式" },
            { label: "造型", value: "几何型" },
            { label: "处理工艺", value: "手工" },
            { label: "水晶种类", value: "粉晶" },
            { label: "销售序列号", value: "eqwr" },
            { label: "生产编号", value: "dasf" },
            { label: "产地", value: "金华" },
            { label: "货号", value: "eqeq" },
            { label: "加印LOGO", value: "不可以" },
            { label: "适用送礼场合", value: "节日" },
            { label: "包装", value: "散装" },
            { label: "加工定制", value: "是" },
            { label: "镶嵌材质", value: "未镶嵌" },
            { label: "尺寸", value: "13mm" },
            { label: "颗数", value: "配件" },
            { label: "品相", value: "通货" },
            { label: "主要下游平台", value: "独立站,抖音" },
            { label: "是否跨境出口专供货源", value: "否" },
            { label: "上市年份/季节", value: "2025年春季" },
            { label: "流行元素", value: "粉水晶" },
            { label: "产品类别", value: "手饰" },
            { label: "种类", value: "手串" },
          ],
          extraInfoDTO: { xl1y: 113 },
          imageUrl:
            "https://cbu01.alicdn.com/img/ibank/O1CN01LICtrW1nhTJMQVcx4_!!2215559905121-0-cib.jpg",
          itemId: "928500638797",
          itemPrice: "35.9",
          offerDetailUrl: "https://detail.1688.com/offer/928500638797.html",
          providerInfo: {
            companyName: "汕头市龙湖区九玖子饰品商行",
            factoryUrl:
              "https://winport.m.1688.com/page/index.html?memberId=b2b-2215559905121fa370",
            providerTags: [{ tagName: "诚信通3年", tagStyle: "GENERAL" }],
            userId: "2215559905121",
          },
          providerKjCustomTags: ["-"],
          providerServices: [
            {
              code: "p-tkl",
              label: "品质退款率",
              originValue: 0.0,
              value: "0%",
            },
            {
              code: "p-xyl",
              label: "客服响应率",
              originValue: 86.0,
              value: "86%",
            },
            {
              code: "p-htl",
              label: "90天回头率",
              originValue: 69.0,
              value: "69%",
            },
            {
              code: "p-fwf",
              label: "综合服务分",
              originValue: 4.1,
              value: "4.1",
            },
            {
              code: "p-dd30d",
              label: "30天订单",
              originValue: 61.0,
              value: "61",
            },
            {
              code: "p-mjs180d",
              label: "180天买家",
              originValue: 257.0,
              value: "257",
            },
            {
              code: "p-allOfferNum",
              label: "全部商品",
              originValue: 363.0,
              value: "363",
            },
            { code: "p-sx30d", label: "近30天上新", value: "-" },
          ],
          purchaseInfos: [
            {
              code: "o-qpl",
              label: "起批量",
              originValue: 2.0,
              value: "2件起批",
            },
            { code: "o-fw", label: "服务", value: "先采后付" },
          ],
          salesInfos: [
            {
              code: "o-xl",
              label: "近一年销量",
              originValue: 113.0,
              value: "113",
            },
          ],
          satisfyRequirements: [],
          shipInfos: [
            {
              code: "o-lyl",
              label: "发货履约率",
              originValue: 100.0,
              value: "100%",
            },
            {
              code: "o-lsl",
              label: "48小时揽收率",
              originValue: 100.0,
              value: "100%",
            },
            { code: "fhd", label: "发货地", value: "浙江省金华市" },
          ],
          title: "原创设计新款天然粉水晶手串手链轻奢精致抖音爆款厂家直销批发",
        },
      ],
    },
    requestIntention: "AUTO",
    selectProviderRequestDTO: {
      intention: "AUTO",
      query: "找可以定制上图这种粉水晶手串的厂商\n\n",
      searchImageUrl:
        "https://cbu01.alicdn.com/img/ibank/O1CN01bbF34N1WljZlw1rNF_!!4611686018427382541-0-overseas_pic.jpg",
      sessionId: "find_provider_285c928b17d44fdebbc7afb0e5de2b8f",
      taskId: "56e46c13870c4a27ab30e45ff60a5122",
      userModel: {
        loginId: "%E6%88%91%E6%98%AF%E9%A6%99%E9%A6%99%E5%91%80hh",
        timestamp: 1763649831972,
        userId: 2862546763,
      },
    },
  },
  reportSummary: "找商结果",
  saveToHistory: true,
  sessionId: "find_provider_285c928b17d44fdebbc7afb0e5de2b8f",
  taskId: "56e46c13870c4a27ab30e45ff60a5122",
  timestamp: 1763666292345,
  title: "找商结果",
};
