// 右侧面板状态
export type TypeRightPanelSide = 'REPORT_CARD' | 'HOT_SALE_PRODUCT' |
  'KEYWORD_SELECT_CARD' | 'KEYWORD_GOOGLE_TRENDS'
  | 'COMPARED_PRODUCT'
  | 'HOT_DETAIL_MODAL' | 'COMPARED_DETAIL_MODAL'
  | 'REVIEW_DETAIL_MODAL' | 'ANALYSIS_DETAIL_MODAL'
  | 'MIGRATED_COMPARED_DETAIL_MODAL' | 'MIGRATED_DETAIL_MODAL';
