export const AREA_CODE_LIST = [
  {
    'areaCode': '+86',
    'areaName': '中国大陆',
    'shotName': 'CN',
    'firstLetter': 'C',
  },
  {
    'areaCode': '+852',
    'areaName': '中国香港',
    'shotName': 'HK',
    'firstLetter': 'H',
  },
  {
    'areaCode': '+853',
    'areaName': '中国澳门',
    'shotName': 'MO',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+886',
    'areaName': '中国台湾',
    'shotName': 'TW',
    'firstLetter': 'T',
  },
  {
    'areaCode': '+51',
    'areaName': '秘鲁',
    'shotName': 'PE',
    'firstLetter': 'P',
  },
  {
    'areaCode': '+48',
    'areaName': '波兰',
    'shotName': 'PL',
    'firstLetter': 'P',
  },
  {
    'areaCode': '+351',
    'areaName': '葡萄牙',
    'shotName': 'PT',
    'firstLetter': 'P',
  },
  {
    'areaCode': '+974',
    'areaName': '卡塔尔',
    'shotName': 'QA',
    'firstLetter': 'Q',
  },
  {
    'areaCode': '+40',
    'areaName': '罗马尼亚',
    'shotName': 'RO',
    'firstLetter': 'R',
  },
  {
    'areaCode': '+381',
    'areaName': '塞尔维亚',
    'shotName': 'RS',
    'firstLetter': 'R',
  },
  {
    'areaCode': '+966',
    'areaName': '沙特阿拉伯',
    'shotName': 'SA',
    'firstLetter': 'S',
  },
  {
    'areaCode': '+248',
    'areaName': '塞舌尔',
    'shotName': 'SC',
    'firstLetter': 'S',
  },
  {
    'areaCode': '+216',
    'areaName': '突尼斯',
    'shotName': 'TN',
    'firstLetter': 'T',
  },
  {
    'areaCode': '+90',
    'areaName': '土耳其',
    'shotName': 'TR',
    'firstLetter': 'T',
  },
  {
    'areaCode': '+58',
    'areaName': '委内瑞拉',
    'shotName': 'VE',
    'firstLetter': 'V',
  },
  {
    'areaCode': '+27',
    'areaName': '南非',
    'shotName': 'ZA',
    'firstLetter': 'Z',
  },
  {
    'areaCode': '+1284',
    'areaName': '英属维尔京群岛',
    'shotName': 'VG',
    'firstLetter': 'V',
  },
  {
    'areaCode': '+355',
    'areaName': '阿尔巴尼亚',
    'shotName': 'AL',
    'firstLetter': 'A',
  },
  {
    'areaCode': '+244',
    'areaName': '安哥拉',
    'shotName': 'AO',
    'firstLetter': 'A',
  },
  {
    'areaCode': '+994',
    'areaName': '阿塞拜疆',
    'shotName': 'AZ',
    'firstLetter': 'A',
  },
  {
    'areaCode': '+226',
    'areaName': '布基纳法索',
    'shotName': 'BF',
    'firstLetter': 'B',
  },
  {
    'areaCode': '+973',
    'areaName': '巴林',
    'shotName': 'BH',
    'firstLetter': 'B',
  },
  {
    'areaCode': '+229',
    'areaName': '贝宁',
    'shotName': 'BJ',
    'firstLetter': 'B',
  },
  {
    'areaCode': '+673',
    'areaName': '文莱',
    'shotName': 'BN',
    'firstLetter': 'B',
  },
  {
    'areaCode': '+591',
    'areaName': '玻利维亚',
    'shotName': 'BO',
    'firstLetter': 'B',
  },
  {
    'areaCode': '+237',
    'areaName': '喀麦隆',
    'shotName': 'CM',
    'firstLetter': 'C',
  },
  {
    'areaCode': '+506',
    'areaName': '哥斯达黎加',
    'shotName': 'CR',
    'firstLetter': 'C',
  },
  {
    'areaCode': '+238',
    'areaName': '佛得角',
    'shotName': 'CV',
    'firstLetter': 'C',
  },
  {
    'areaCode': '+357',
    'areaName': '塞浦路斯',
    'shotName': 'CY',
    'firstLetter': 'C',
  },
  {
    'areaCode': '+253',
    'areaName': '吉布提',
    'shotName': 'DJ',
    'firstLetter': 'D',
  },
  {
    'areaCode': '+241',
    'areaName': '加蓬',
    'shotName': 'GA',
    'firstLetter': 'G',
  },
  {
    'areaCode': '+1473',
    'areaName': '格林纳达',
    'shotName': 'GD',
    'firstLetter': 'G',
  },
  {
    'areaCode': '+995',
    'areaName': '格鲁吉亚',
    'shotName': 'GE',
    'firstLetter': 'G',
  },
  {
    'areaCode': '+220',
    'areaName': '冈比亚',
    'shotName': 'GM',
    'firstLetter': 'G',
  },
  {
    'areaCode': '+224',
    'areaName': '几内亚',
    'shotName': 'GN',
    'firstLetter': 'G',
  },
  {
    'areaCode': '+240',
    'areaName': '赤道几内亚',
    'shotName': 'GQ',
    'firstLetter': 'G',
  },
  {
    'areaCode': '+502',
    'areaName': '危地马拉',
    'shotName': 'GT',
    'firstLetter': 'G',
  },
  {
    'areaCode': '+245',
    'areaName': '几内亚比绍',
    'shotName': 'GW',
    'firstLetter': 'G',
  },
  {
    'areaCode': '+592',
    'areaName': '圭亚那',
    'shotName': 'GY',
    'firstLetter': 'G',
  },
  {
    'areaCode': '+504',
    'areaName': '洪都拉斯',
    'shotName': 'HN',
    'firstLetter': 'H',
  },
  {
    'areaCode': '+385',
    'areaName': '克罗地亚',
    'shotName': 'HR',
    'firstLetter': 'H',
  },
  {
    'areaCode': '+1876',
    'areaName': '牙买加',
    'shotName': 'JM',
    'firstLetter': 'J',
  },
  {
    'areaCode': '+254',
    'areaName': '肯尼亚',
    'shotName': 'KE',
    'firstLetter': 'K',
  },
  {
    'areaCode': '+269',
    'areaName': '科摩罗',
    'shotName': 'KM',
    'firstLetter': 'K',
  },
  {
    'areaCode': '+965',
    'areaName': '科威特',
    'shotName': 'KW',
    'firstLetter': 'K',
  },
  {
    'areaCode': '+1345',
    'areaName': '开曼群岛',
    'shotName': 'KY',
    'firstLetter': 'K',
  },
  {
    'areaCode': '+266',
    'areaName': '莱索托',
    'shotName': 'LS',
    'firstLetter': 'L',
  },
  {
    'areaCode': '+371',
    'areaName': '拉脱维亚',
    'shotName': 'LV',
    'firstLetter': 'L',
  },
  {
    'areaCode': '+373',
    'areaName': '摩尔多瓦',
    'shotName': 'MD',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+261',
    'areaName': '马达加斯加',
    'shotName': 'MG',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+223',
    'areaName': '马里',
    'shotName': 'ML',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+222',
    'areaName': '毛里塔尼亚',
    'shotName': 'MR',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+230',
    'areaName': '毛里求斯',
    'shotName': 'MU',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+265',
    'areaName': '马拉维',
    'shotName': 'MW',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+258',
    'areaName': '莫桑比克',
    'shotName': 'MZ',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+264',
    'areaName': '纳米比亚',
    'shotName': 'NA',
    'firstLetter': 'N',
  },
  {
    'areaCode': '+227',
    'areaName': '尼日尔',
    'shotName': 'NE',
    'firstLetter': 'N',
  },
  {
    'areaCode': '+505',
    'areaName': '尼加拉瓜',
    'shotName': 'NI',
    'firstLetter': 'N',
  },
  {
    'areaCode': '+968',
    'areaName': '阿曼',
    'shotName': 'OM',
    'firstLetter': 'O',
  },
  {
    'areaCode': '+675',
    'areaName': '巴布亚新几内亚',
    'shotName': 'PG',
    'firstLetter': 'P',
  },
  {
    'areaCode': '+970',
    'areaName': '巴勒斯坦',
    'shotName': 'PS',
    'firstLetter': 'P',
  },
  {
    'areaCode': '+250',
    'areaName': '卢旺达',
    'shotName': 'RW',
    'firstLetter': 'R',
  },
  {
    'areaCode': '+386',
    'areaName': '斯洛文尼亚',
    'shotName': 'SI',
    'firstLetter': 'S',
  },
  {
    'areaCode': '+421',
    'areaName': '斯洛伐克',
    'shotName': 'SK',
    'firstLetter': 'S',
  },
  {
    'areaCode': '+232',
    'areaName': '塞拉利昂',
    'shotName': 'SL',
    'firstLetter': 'S',
  },
  {
    'areaCode': '+221',
    'areaName': '塞内加尔',
    'shotName': 'SN',
    'firstLetter': 'S',
  },
  {
    'areaCode': '+597',
    'areaName': '苏里南',
    'shotName': 'SR',
    'firstLetter': 'S',
  },
  {
    'areaCode': '+503',
    'areaName': '萨尔瓦多',
    'shotName': 'SV',
    'firstLetter': 'S',
  },
  {
    'areaCode': '+268',
    'areaName': '斯威士兰',
    'shotName': 'SZ',
    'firstLetter': 'S',
  },
  {
    'areaCode': '+235',
    'areaName': '乍得',
    'shotName': 'TD',
    'firstLetter': 'T',
  },
  {
    'areaCode': '+228',
    'areaName': '多哥',
    'shotName': 'TG',
    'firstLetter': 'T',
  },
  {
    'areaCode': '+992',
    'areaName': '塔吉克斯坦',
    'shotName': 'TJ',
    'firstLetter': 'T',
  },
  {
    'areaCode': '+993',
    'areaName': '土库曼斯坦',
    'shotName': 'TM',
    'firstLetter': 'T',
  },
  {
    'areaCode': '+1868',
    'areaName': '特立尼达和多巴哥',
    'shotName': 'TT',
    'firstLetter': 'T',
  },
  {
    'areaCode': '+255',
    'areaName': '坦桑尼亚',
    'shotName': 'TZ',
    'firstLetter': 'T',
  },
  {
    'areaCode': '+256',
    'areaName': '乌干达',
    'shotName': 'UG',
    'firstLetter': 'U',
  },
  {
    'areaCode': '+598',
    'areaName': '乌拉圭',
    'shotName': 'UY',
    'firstLetter': 'U',
  },
  {
    'areaCode': '+998',
    'areaName': '乌兹别克斯坦',
    'shotName': 'UZ',
    'firstLetter': 'U',
  },
  {
    'areaCode': '+967',
    'areaName': '也门',
    'shotName': 'YE',
    'firstLetter': 'Y',
  },
  {
    'areaCode': '+260',
    'areaName': '赞比亚',
    'shotName': 'ZM',
    'firstLetter': 'Z',
  },
  {
    'areaCode': '+263',
    'areaName': '津巴布韦',
    'shotName': 'ZW',
    'firstLetter': 'Z',
  },
  {
    'areaCode': '+376',
    'areaName': '安道尔共和国',
    'shotName': 'AD',
    'firstLetter': 'A',
  },
  {
    'areaCode': '+93',
    'areaName': '阿富汗',
    'shotName': 'AF',
    'firstLetter': 'A',
  },
  {
    'areaCode': '+374',
    'areaName': '亚美尼亚',
    'shotName': 'AM',
    'firstLetter': 'A',
  },
  {
    'areaCode': '+387',
    'areaName': '波斯尼亚和黑塞哥维那',
    'shotName': 'BA',
    'firstLetter': 'B',
  },
  {
    'areaCode': '+880',
    'areaName': '孟加拉国',
    'shotName': 'BD',
    'firstLetter': 'B',
  },
  {
    'areaCode': '+257',
    'areaName': '布隆迪',
    'shotName': 'BI',
    'firstLetter': 'B',
  },
  {
    'areaCode': '+267',
    'areaName': '博茨瓦纳',
    'shotName': 'BW',
    'firstLetter': 'B',
  },
  {
    'areaCode': '+243',
    'areaName': '刚果(金)',
    'shotName': 'CD',
    'firstLetter': 'C',
  },
  {
    'areaCode': '+236',
    'areaName': '中非',
    'shotName': 'CF',
    'firstLetter': 'C',
  },
  {
    'areaCode': '+242',
    'areaName': '刚果(布)',
    'shotName': 'CG',
    'firstLetter': 'C',
  },
  {
    'areaCode': '+225',
    'areaName': '科特迪瓦',
    'shotName': 'CI',
    'firstLetter': 'C',
  },
  {
    'areaCode': '+599',
    'areaName': '库拉索岛',
    'shotName': 'CW',
    'firstLetter': 'C',
  },
  {
    'areaCode': '+420',
    'areaName': '捷克共和国',
    'shotName': 'CZ',
    'firstLetter': 'C',
  },
  {
    'areaCode': '+1809',
    'areaName': '多米尼加共和国',
    'shotName': 'DO',
    'firstLetter': 'D',
  },
  {
    'areaCode': '+213',
    'areaName': '阿尔及利亚',
    'shotName': 'DZ',
    'firstLetter': 'D',
  },
  {
    'areaCode': '+593',
    'areaName': '厄瓜多尔',
    'shotName': 'EC',
    'firstLetter': 'E',
  },
  {
    'areaCode': '+233',
    'areaName': '加纳',
    'shotName': 'GH',
    'firstLetter': 'G',
  },
  {
    'areaCode': '+964',
    'areaName': '伊拉克',
    'shotName': 'IQ',
    'firstLetter': 'I',
  },
  {
    'areaCode': '+7',
    'areaName': '哈萨克斯坦',
    'shotName': 'KZ',
    'firstLetter': 'K',
  },
  {
    'areaCode': '+856',
    'areaName': '老挝',
    'shotName': 'LA',
    'firstLetter': 'L',
  },
  {
    'areaCode': '+961',
    'areaName': '黎巴嫩',
    'shotName': 'LB',
    'firstLetter': 'L',
  },
  {
    'areaCode': '+231',
    'areaName': '利比里亚',
    'shotName': 'LR',
    'firstLetter': 'L',
  },
  {
    'areaCode': '+218',
    'areaName': '利比亚',
    'shotName': 'LY',
    'firstLetter': 'L',
  },
  {
    'areaCode': '+382',
    'areaName': '黑山共和国',
    'shotName': 'ME',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+590',
    'areaName': '圣马丁',
    'shotName': 'MF',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+389',
    'areaName': '马其顿',
    'shotName': 'MK',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+95',
    'areaName': '缅甸',
    'shotName': 'MM',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+92',
    'areaName': '巴基斯坦',
    'shotName': 'PK',
    'firstLetter': 'P',
  },
  {
    'areaCode': '+1787',
    'areaName': '波多黎各',
    'shotName': 'PR',
    'firstLetter': 'P',
  },
  {
    'areaCode': '+252',
    'areaName': '索马里',
    'shotName': 'SO',
    'firstLetter': 'S',
  },
  {
    'areaCode': '+1784',
    'areaName': '圣文森特和格林纳丁斯',
    'shotName': 'VC',
    'firstLetter': 'V',
  },
  {
    'areaCode': '+977',
    'areaName': '尼泊尔',
    'shotName': 'NP',
    'firstLetter': 'N',
  },
  {
    'areaCode': '+383',
    'areaName': '科索沃',
    // XK 是欧盟的标准，KS是菜鸟库的标准
    'shotName': 'KS',
    'firstLetter': 'K',
  },
  {
    'areaCode': '+356',
    'areaName': '马耳他',
    'shotName': 'MT',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+82',
    'areaName': '韩国',
    'shotName': 'KR',
    'firstLetter': 'K',
  },
  {
    'areaCode': '+81',
    'areaName': '日本',
    'shotName': 'JP',
    'firstLetter': 'J',
  },
  {
    'areaCode': '+1',
    'areaName': '美国',
    'shotName': 'US',
    'firstLetter': 'U',
  },
  // {
  //   "areaCode": "+1",
  //   "areaName": "加拿大",
  //   "shotName": "CA",
  //   "firstLetter": "C"
  // },
  {
    'areaCode': '+44',
    'areaName': '英国',
    'shotName': 'GB',
    'firstLetter': 'G',
  },
  {
    'areaCode': '+61',
    'areaName': '澳大利亚',
    'shotName': 'AU',
    'firstLetter': 'A',
  },
  {
    'areaCode': '+65',
    'areaName': '新加坡',
    'shotName': 'SG',
    'firstLetter': 'S',
  },
  {
    'areaCode': '+60',
    'areaName': '马来西亚',
    'shotName': 'MY',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+66',
    'areaName': '泰国',
    'shotName': 'TH',
    'firstLetter': 'T',
  },
  {
    'areaCode': '+84',
    'areaName': '越南',
    'shotName': 'VN',
    'firstLetter': 'V',
  },
  {
    'areaCode': '+63',
    'areaName': '菲律宾',
    'shotName': 'PH',
    'firstLetter': 'P',
  },
  {
    'areaCode': '+62',
    'areaName': '印度尼西亚',
    'shotName': 'ID',
    'firstLetter': 'I',
  },
  {
    'areaCode': '+49',
    'areaName': '德国',
    'shotName': 'DE',
    'firstLetter': 'D',
  },
  {
    'areaCode': '+39',
    'areaName': '意大利',
    'shotName': 'IT',
    'firstLetter': 'I',
  },
  {
    'areaCode': '+33',
    'areaName': '法国',
    'shotName': 'FR',
    'firstLetter': 'F',
  },
  // {
  //   "areaCode": "+7",
  //   "areaName": "俄罗斯",
  //   "shotName": "RU",
  //   "firstLetter": "R"
  // },
  {
    'areaCode': '+64',
    'areaName': '新西兰',
    'shotName': 'NZ',
    'firstLetter': 'N',
  },
  {
    'areaCode': '+31',
    'areaName': '荷兰',
    'shotName': 'NL',
    'firstLetter': 'N',
  },
  {
    'areaCode': '+46',
    'areaName': '瑞典',
    'shotName': 'SE',
    'firstLetter': 'S',
  },
  {
    'areaCode': '+380',
    'areaName': '乌克兰',
    'shotName': 'UA',
    'firstLetter': 'U',
  },
  {
    'areaCode': '+971',
    'areaName': '阿联酋',
    'shotName': 'AE',
    'firstLetter': 'A',
  },
  {
    'areaCode': '+54',
    'areaName': '阿根廷',
    'shotName': 'AR',
    'firstLetter': 'A',
  },
  {
    'areaCode': '+43',
    'areaName': '奥地利',
    'shotName': 'AT',
    'firstLetter': 'A',
  },
  {
    'areaCode': '+32',
    'areaName': '比利时',
    'shotName': 'BE',
    'firstLetter': 'B',
  },
  {
    'areaCode': '+359',
    'areaName': '保加利亚',
    'shotName': 'BG',
    'firstLetter': 'B',
  },
  {
    'areaCode': '+55',
    'areaName': '巴西',
    'shotName': 'BR',
    'firstLetter': 'B',
  },
  {
    'areaCode': '+1242',
    'areaName': '巴哈马',
    'shotName': 'BS',
    'firstLetter': 'B',
  },
  {
    'areaCode': '+375',
    'areaName': '白俄罗斯',
    'shotName': 'BY',
    'firstLetter': 'B',
  },
  {
    'areaCode': '+501',
    'areaName': '伯利兹',
    'shotName': 'BZ',
    'firstLetter': 'B',
  },
  {
    'areaCode': '+41',
    'areaName': '瑞士',
    'shotName': 'CH',
    'firstLetter': 'C',
  },
  {
    'areaCode': '+56',
    'areaName': '智利',
    'shotName': 'CL',
    'firstLetter': 'C',
  },
  {
    'areaCode': '+57',
    'areaName': '哥伦比亚',
    'shotName': 'CO',
    'firstLetter': 'C',
  },
  {
    'areaCode': '+45',
    'areaName': '丹麦',
    'shotName': 'DK',
    'firstLetter': 'D',
  },
  {
    'areaCode': '+372',
    'areaName': '爱沙尼亚',
    'shotName': 'EE',
    'firstLetter': 'E',
  },
  {
    'areaCode': '+20',
    'areaName': '埃及',
    'shotName': 'EG',
    'firstLetter': 'E',
  },
  {
    'areaCode': '+34',
    'areaName': '西班牙',
    'shotName': 'ES',
    'firstLetter': 'E',
  },
  {
    'areaCode': '+358',
    'areaName': '芬兰',
    'shotName': 'FI',
    'firstLetter': 'F',
  },
  {
    'areaCode': '+30',
    'areaName': '希腊',
    'shotName': 'GR',
    'firstLetter': 'G',
  },
  {
    'areaCode': '+36',
    'areaName': '匈牙利',
    'shotName': 'HU',
    'firstLetter': 'H',
  },
  {
    'areaCode': '+353',
    'areaName': '爱尔兰',
    'shotName': 'IE',
    'firstLetter': 'I',
  },
  {
    'areaCode': '+972',
    'areaName': '以色列',
    'shotName': 'IL',
    'firstLetter': 'I',
  },
  {
    'areaCode': '+91',
    'areaName': '印度',
    'shotName': 'IN',
    'firstLetter': 'I',
  },
  {
    'areaCode': '+962',
    'areaName': '约旦',
    'shotName': 'JO',
    'firstLetter': 'J',
  },
  {
    'areaCode': '+996',
    'areaName': '吉尔吉斯斯坦',
    'shotName': 'KG',
    'firstLetter': 'K',
  },
  {
    'areaCode': '+855',
    'areaName': '柬埔寨',
    'shotName': 'KH',
    'firstLetter': 'K',
  },
  {
    'areaCode': '+94',
    'areaName': '斯里兰卡',
    'shotName': 'LK',
    'firstLetter': 'L',
  },
  {
    'areaCode': '+370',
    'areaName': '立陶宛',
    'shotName': 'LT',
    'firstLetter': 'L',
  },
  {
    'areaCode': '+352',
    'areaName': '卢森堡',
    'shotName': 'LU',
    'firstLetter': 'L',
  },
  {
    'areaCode': '+212',
    'areaName': '摩洛哥',
    'shotName': 'MA',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+976',
    'areaName': '蒙古',
    'shotName': 'MN',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+960',
    'areaName': '马尔代夫',
    'shotName': 'MV',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+52',
    'areaName': '墨西哥',
    'shotName': 'MX',
    'firstLetter': 'M',
  },
  {
    'areaCode': '+234',
    'areaName': '尼日利亚',
    'shotName': 'NG',
    'firstLetter': 'N',
  },
  {
    'areaCode': '+47',
    'areaName': '挪威',
    'shotName': 'NO',
    'firstLetter': 'N',
  },
  {
    'areaCode': '+507',
    'areaName': '巴拿马',
    'shotName': 'PA',
    'firstLetter': 'P',
  },
];

// 不同国家的手机号规则
export const OVERSEAS_MOBILE_MAP = {
  // '+86': /^(\+86-)?(1\d{10}|1\d{10}\-\d{3,5})$/,
  '+65': /^(\+65-)?[13689]\d{6,7}$/,
  '+7': /^(\+7-)?\d{6,15}$/,
  '+84': /^(\+84-)?(0){0,1}[1-9]\d{6,9}$/,
  '+853': /^(\+853-)?6\d{7}$/,
  '+61': /^(\+61-)?(0){0,1}4\d{8,9}$/,
  '+971': /^(\+971-)?\d{6,12}$/,
  '+54': /^(\+54-)?\d{6,12}$/,
  '+43': /^(\+43-)?\d{6,13}$/,
  '+372': /^(\+372-)?\d{6,12}$/,
  '+20': /^(\+20-)?\d{6,12}$/,
  '+353': /^(\+353-)?\d{6,12}$/,
  '+355': /^(\+355-)?\d{6,15}$/,
  '+244': /^(\+244-)?\d{6,15}$/,
  '+994': /^(\+994-)?\d{6,15}$/,
  '+968': /^(\+968-)?\d{6,15}$/,
  '+376': /^(\+376-)?\d{6,15}$/,
  '+93': /^(\+93-)?\d{6,15}$/,
  '+213': /^(\+213-)?\d{6,15}$/,
  '+32': /^(\+32-)?\d{6,12}$/,
  '+359': /^(\+359-)?\d{6,12}$/,
  '+55': /^(\+55-)?[0-9]{5}-[0-9]{3}$|^(\+55-)?[0-9]{8}$/,
  '+1242': /^(\+1242-)?\d{6,12}$/,
  '+375': /^(\+375-)?\d{6,12}$/,
  '+501': /^(\+501-)?\d{6,12}$/,
  '+507': /^(\+507-)?\d{6,12}$/,
  '+51': /^(\+51-)?\d{6,12}$/,
  '+48': /^(\+48-)?\d{6,12}$/,
  '+226': /^(\+226-)?\d{6,15}$/,
  '+973': /^(\+973-)?\d{6,15}$/,
  '+229': /^(\+229-)?\d{6,15}$/,
  '+591': /^(\+591-)?\d{6,15}$/,
  '+675': /^(\+675-)?\d{6,15}$/,
  '+970': /^(\+970-)?\d{6,15}$/,
  '+387': /^(\+387-)?\d{6,15}$/,
  '+257': /^(\+257-)?\d{6,15}$/,
  '+267': /^(\+267-)?\d{6,15}$/,
  '+92': /^(\+92-)?\d{6,15}$/,
  '+1787': /^(\+1787-)?\d{6,15}$/,
  '+240': /^(\+240-)?\d{6,15}$/,
  '+49': /^(\+49-)?1(\d{5,6}|\d{9,12})$/,
  '+45': /^(\+45-)?\d{6,12}$/,
  '+228': /^(\+228-)?\d{6,15}$/,
  '+1809': /^(\+1809-)?\d{6,15}$/,
  '+593': /^(\+593-)?\d{6,15}$/,
  '+63': /^(\+63-)?(0){0,1}[24579](\d{7,9}|\d{12})$/,
  '+33': /^(\+33-)?(\d{6}|\d{8,10})$/,
  '+358': /^(\+358-)?\d{6,12}$/,
  '+238': /^(\+238-)?\d{6,15}$/,
  '+57': /^(\+57-)?\d{6,12}$/,
  '+506': /^(\+506-)?\d{6,15}$/,
  '+1473': /^(\+1473-)?\d{6,15}$/,
  '+995': /^(\+995-)?\d{6,15}$/,
  '+220': /^(\+220-)?\d{6,15}$/,
  '+592': /^(\+592-)?\d{6,15}$/,
  '+243': /^(\+243-)?\d{6,15}$/,
  '+242': /^(\+242-)?\d{6,15}$/,
  '+82': /^(\+82-)?0{0,1}[71](?:\d{8}|\d{9})$/,
  '+31': /^(\+31-)?6\d{8}$/,
  '+504': /^(\+504-)?\d{6,15}$/,
  '+382': /^(\+382-)?\d{6,15}$/,
  '+1': /^(\+1-)?\d{10,12}$/,
  '+996': /^(\+996-)?\d{6,12}$/,
  '+855': /^(\+855-)?\d{6,12}$/,
  '+253': /^(\+253-)?\d{6,15}$/,
  '+241': /^(\+241-)?\d{6,15}$/,
  '+224': /^(\+224-)?\d{6,15}$/,
  '+245': /^(\+245-)?\d{6,15}$/,
  '+263': /^(\+263-)?\d{6,15}$/,
  '+420': /^(\+420-)?\d{6,15}$/,
  '+233': /^(\+233-)?\d{9,10}$/,
  '+974': /^(\+974-)?\d{6,12}$/,
  '+237': /^(\+237-)?\d{6,15}$/,
  '+385': /^(\+385-)?\d{6,15}$/,
  '+254': /^(\+254-)?\d{6,15}$/,
  '+269': /^(\+269-)?\d{6,15}$/,
  '+965': /^(\+965-)?\d{6,15}$/,
  '+1345': /^(\+1345-)?\d{6,15}$/,
  '+225': /^(\+225-)?\d{6,15}$/,
  '+599': /^(\+599-)?\d{6,15}$/,
  '+370': /^(\+370-)?\d{6,12}$/,
  '+352': /^(\+352-)?\d{6,12}$/,
  '+40': /^(\+40-)?\d{6,12}$/,
  '+266': /^(\+266-)?\d{6,15}$/,
  '+371': /^(\+371-)?\d{6,15}$/,
  '+250': /^(\+250-)?\d{6,15}$/,
  '+856': /^(\+856-)?\d{6,15}$/,
  '+961': /^(\+961-)?\d{6,15}$/,
  '+231': /^(\+231-)?\d{6,15}$/,
  '+218': /^(\+218-)?\d{6,15}$/,
  '+60': /^(\+60-)?(0){0,1}1\d{8,10}$/,
  '+212': /^(\+212-)?\d{6,12}$/,
  '+976': /^(\+976-)?\d{6,12}$/,
  '+960': /^(\+960-)?\d{6,12}$/,
  '+52': /^(\+52-)?\d{6,12}$/,
  '+373': /^(\+373-)?\d{6,15}$/,
  '+261': /^(\+261-)?\d{6,15}$/,
  '+223': /^(\+223-)?\d{6,15}$/,
  '+222': /^(\+222-)?\d{6,15}$/,
  '+230': /^(\+230-)?\d{6,15}$/,
  '+265': /^(\+265-)?\d{6,15}$/,
  '+258': /^(\+258-)?\d{6,15}$/,
  '+880': /^(\+880-)?\d{6,15}$/,
  '+389': /^(\+389-)?\d{6,15}$/,
  '+95': /^(\+95-)?\d{6,15}$/,
  '+356': /^(\+356-)?\d{6,15}$/,
  '+234': /^(\+234-)?\d{6,12}$/,
  '+47': /^(\+47-)?\d{6,12}$/,
  '+27': /^(\+27-)?\d{6,12}$/,
  '+264': /^(\+264-)?\d{6,15}$/,
  '+227': /^(\+227-)?\d{6,15}$/,
  '+505': /^(\+505-)?\d{6,15}$/,
  '+977': /^(\+977-)?\d{6,15}$/,
  '+351': /^(\+351-)?\d{6,12}$/,
  '+81': /^(\+81-)?0{0,1}[789](?:\d{8}|\d{9})$/,
  '+46': /^(\+46-)?[124-7](\d{8}|\d{10}|\d{12})$/,
  '+41': /^(\+41-)?\d{6,12}$/,
  '+94': /^(\+94-)?\d{6,12}$/,
  '+381': /^(\+381-)?\d{6,12}$/,
  '+248': /^(\+248-)?\d{6,12}$/,
  '+966': /^(\+966-)?\d{6,12}$/,
  '+357': /^(\+357-)?\d{6,15}$/,
  '+386': /^(\+386-)?\d{6,15}$/,
  '+421': /^(\+421-)?\d{6,15}$/,
  '+232': /^(\+232-)?\d{6,15}$/,
  '+221': /^(\+221-)?\d{6,15}$/,
  '+597': /^(\+597-)?\d{6,15}$/,
  '+503': /^(\+503-)?\d{6,15}$/,
  '+268': /^(\+268-)?\d{6,15}$/,
  '+590': /^(\+590-)?\d{6,15}$/,
  '+252': /^(\+252-)?\d{6,15}$/,
  '+1784': /^(\+1784-)?\d{6,15}$/,
  '+886': /^(\+886-)?0{0,1}[679](?:\d{7}|\d{8}|\d{10})$/,
  '+66': /^(\+66-)?(0){0,1}[13456789]\d{7,8}$/,
  '+216': /^(\+216-)?\d{6,12}$/,
  '+90': /^(\+90-)?\d{6,12}$/,
  '+992': /^(\+992-)?\d{6,15}$/,
  '+993': /^(\+993-)?\d{6,15}$/,
  '+1868': /^(\+1868-)?\d{6,15}$/,
  '+255': /^(\+255-)?\d{6,15}$/,
  '+380': /^(\+380-)?[3-79]\d{8,9}$/,
  '+58': /^(\+58-)?\d{6,12}$/,
  '+673': /^(\+673-)?\d{6,15}$/,
  '+502': /^(\+502-)?\d{6,15}$/,
  '+256': /^(\+256-)?\d{6,15}$/,
  '+598': /^(\+598-)?\d{6,15}$/,
  '+998': /^(\+998-)?\d{6,15}$/,
  '+852': /^(\+852-)?0{0,1}[1456789](?:\d{7}|\d{8}|\d{12})$/,
  '+64': /^(\+64-)?[278]\d{7,9}$/,
  '+34': /^(\+34-)?\d{6,12}$/,
  '+36': /^(\+36-)?\d{6,12}$/,
  '+30': /^(\+30-)?\d{6,12}$/,
  '+44': /^(\+44-)?[347-9](\d{8,9}|\d{11,12})$/,
  '+62': /^(\+62-)?[2-9]\d{7,11}$/,
  '+39': /^(\+39-)?[37]\d{8,11}$/,
  '+972': /^(\+972-)?\d{6,12}$/,
  '+91': /^(\+91-)?\d{6,12}$/,
  '+962': /^(\+962-)?\d{6,12}$/,
  '+1284': /^(\+1284-)?\d{6,12}$/,
  '+1876': /^(\+1876-)?\d{6,15}$/,
  '+967': /^(\+967-)?\d{6,15}$/,
  '+374': /^(\+374-)?\d{6,15}$/,
  '+964': /^(\+964-)?\d{6,15}$/,
  '+56': /^(\+56-)?\d{6,12}$/,
  '+235': /^(\+235-)?\d{6,15}$/,
  '+260': /^(\+260-)?\d{6,15}$/,
  '+236': /^(\+236-)?\d{6,15}$/,
};

// 协议
export const agreement = [
  {
    name: '《1688跨境货通全球入驻协议》',
    link: 'https://terms.alicdn.com/legal-agreement/terms/b_platform_service_agreement/20231215171709856/20231215171709856.html?spm=a2639r.crossborderofferlist.0.0.34541576OcnC1E',
  },
  {
    name: '《1688数智供应链技术服务协议》',
    link: 'https://terms.alicdn.com/legal-agreement/terms/b_end_product_protocol/20240108153142381/20240108153142381.html?spm=a2639r.crossborderofferlist.0.0.34541576OcnC1E',
  },
  {
    name: '《中国商家个人信息跨境传输同意函》',
    link: ' https://contract.alibaba-inc.com/documentcoop/editor/page/preview?spm=a2639r.crossborderofferlist.0.0.34541576OcnC1E&securityDocumentId=Gy4d2Q5-NkjZp9FBHiux_Q&securityDialogDocumentId=&dialogShowType=always&securityAgreementId=S9BeDbRAJfLi25jx0zwo1Q&_authType=SAML#/',
  },
  {
    name: '《支付宝付款授权服务协议》',
    link: 'https://render.alipay.com/p/yuyan/180020010001196791/preview.html?agreementId=AG00000051',
  },
  {
    name: '《1688大严选帮卖技术服务协议》',
    link: 'https://terms.alicdn.com/legal-agreement/terms/common_platform_service/20241223102539751/20241223102539751.html?spm=a2639r.crossborderofferlist.0.0.50f21576ceCtV2',
  },
  // {
  //   name: '《海外仓协议》',
  //   link: '',
  // },
]