// 国家名称到 ISO 3166-1 alpha-2 代码的映射
export const countryMapping: Record<string, string> = {
  // 中文国家名称映射
  美国: 'us',
  中国: 'cn',
  英国: 'gb',
  德国: 'de',
  法国: 'fr',
  日本: 'jp',
  韩国: 'kr',
  加拿大: 'ca',
  澳大利亚: 'au',
  意大利: 'it',
  西班牙: 'es',
  荷兰: 'nl',
  瑞士: 'ch',
  瑞典: 'se',
  挪威: 'no',
  丹麦: 'dk',
  芬兰: 'fi',
  俄罗斯: 'ru',
  印度: 'in',
  巴西: 'br',
  墨西哥: 'mx',
  阿根廷: 'ar',
  南非: 'za',
  新加坡: 'sg',
  马来西亚: 'my',
  泰国: 'th',
  印度尼西亚: 'id',
  菲律宾: 'ph',
  越南: 'vn',
  土耳其: 'tr',
  以色列: 'il',
  阿联酋: 'ae',
  沙特阿拉伯: 'sa',
  埃及: 'eg',
  尼日利亚: 'ng',
  肯尼亚: 'ke',
  摩洛哥: 'ma',
  智利: 'cl',
  哥伦比亚: 'co',
  秘鲁: 'pe',
  波兰: 'pl',
  捷克: 'cz',
  匈牙利: 'hu',
  奥地利: 'at',
  比利时: 'be',
  葡萄牙: 'pt',
  希腊: 'gr',
  爱尔兰: 'ie',
  新西兰: 'nz',

  // 英文国家名称映射
  'United States': 'us',
  USA: 'us',
  China: 'cn',
  'United Kingdom': 'gb',
  UK: 'gb',
  Germany: 'de',
  France: 'fr',
  Japan: 'jp',
  'South Korea': 'kr',
  Korea: 'kr',
  Canada: 'ca',
  Australia: 'au',
  Italy: 'it',
  Spain: 'es',
  Netherlands: 'nl',
  Switzerland: 'ch',
  Sweden: 'se',
  Norway: 'no',
  Denmark: 'dk',
  Finland: 'fi',
  Russia: 'ru',
  India: 'in',
  Brazil: 'br',
  Mexico: 'mx',
  Argentina: 'ar',
  'South Africa': 'za',
  Singapore: 'sg',
  Malaysia: 'my',
  Thailand: 'th',
  Indonesia: 'id',
  Philippines: 'ph',
  Vietnam: 'vn',
  Turkey: 'tr',
  Israel: 'il',
  UAE: 'ae',
  'Saudi Arabia': 'sa',
  Egypt: 'eg',
  Nigeria: 'ng',
  Kenya: 'ke',
  Morocco: 'ma',
  Chile: 'cl',
  Colombia: 'co',
  Peru: 'pe',
  Poland: 'pl',
  'Czech Republic': 'cz',
  Hungary: 'hu',
  Austria: 'at',
  Belgium: 'be',
  Portugal: 'pt',
  Greece: 'gr',
  Ireland: 'ie',
  'New Zealand': 'nz',
};

// 获取国家的 ISO 代码
export const getCountryCode = (countryName: string): string | undefined => {
  return countryMapping[countryName];
};

// 创建 flag-icons 的类名
export const getFlagClass = (countryName: string): string => {
  const code = getCountryCode(countryName);
  return code ? `fi fi-${code}` : '';
};
