export const LOG_KEYS = {
  AGENT_HOME: {
    BUTTON: {
      INSIGHT: '/alphashop.agent-home-page.button.insight',
      SOURCING: '/alphashop.agent-home-page.button.sourcing',
      DESIGN: '/alphashop.agent-home-page.button.design',
      INQUIRY: '/alphashop.agent-home-page.button.inquiry',
      CHAT: '/alphashop.agent-home-page.button.chat',
    },
    SIDEBAR: {
      LOGO: '/alphashop.agent-home-page.sidebar.logo',
      HOME: '/alphashop.agent-home-page.sidebar.home',
      INSIGHT: '/alphashop.agent-home-page.sidebar.insight',
      SOURCING: '/alphashop.agent-home-page.sidebar.sourcing',
      DESIGN: '/alphashop.agent-home-page.sidebar.design',
      INQUIRY: '/alphashop.agent-home-page.sidebar.inquiry',
      CHAT: '/alphashop.agent-home-page.sidebar.chat',
      SET: '/alphashop.agent-home-page.sidebar.set',
      OPENPLATFORM: '/alphashop.agent-home-page.sidebar.openplatform',
      HOT_RANKING: '/alphashop.agent-home-page.sidebar.rankinglist',
    },
    CHATBOX: {
      INSIGHT_CLICK: '/alphashop.agent-home-page.chatbox.insightclick',
      INSIGHT_CHANNEL: '/alphashop.agent-home-page.chatbox.insightchannel',
      INSIGHT_COUNTRY: '/alphashop.agent-home-page.chatbox.insightcountry',
      SOURCING_CLICK: '/alphashop.agent-home-page.chatbox.sourcingclick',
      SOURCING_MODE: '/alphashop.agent-home-page.chatbox.sourcingmode',
      SOURCING_IMG: '/alphashop.agent-home-page.chatbox.sourcingimg',
      DESIGN_CLICK: '/alphashop.agent-home-page.chatbox.designclick',
      DESIGN_ENHANCED: '/alphashop.agent-home-page.chatbox.designenhanced',
      DESIGN_IMG: '/alphashop.agent-home-page.chatbox.designimg',
      DESIGN_URL: '/alphashop.agent-home-page.chatbox.designurl',
      INQUIRY_CLICK: '/alphashop.agent-home-page.chatbox.inquiryclick',
      CHAT_CLICK: '/alphashop.agent-home-page.chatbox.chatclick',
    },
    CARD: {
      INSIGHT_NEW: '/alphashop.agent-home-page.card.insightnew',
      INSIGHT_COUNTRY: '/alphashop.agent-home-page.card.insightcountry',
      INSIGHT_PLATFORM: '/alphashop.agent-home-page.card.insightplayform',
      INSIGHT_IMPROVE: '/alphashop.agent-home-page.card.insightimprove',
      IMG_SEARCH: '/alphashop.agent-home-page.card.imgsearch',
      DESIGN_MODEL: '/alphashop.agent-home-page.card.designmodel',
      DESIGN_MKT_IMG: '/alphashop.agent-home-page.card.designmktimg',
      DESIGN_BG_IMG: '/alphashop.agent-home-page.card.designbgimg',
      DESIGN_STYLE: '/alphashop.agent-home-page.card.designstyle',
      DESIGN_TRANS: '/alphashop.agent-home-page.card.designtrans',
    },
    RANKING: {
      OPPORTUNITY: '/alphashop.agent-home-page.rankinglist.opportunity',
      ALL_ITEM: '/alphashop.agent-home-page.rankinglist.allitem',
    },
    SHOWCASE: {
      INSIGHT_VIEW: '/alphashop.agent-home-page.showcase.insightview',
      INSIGHT_SAME: '/alphashop.agent-home-page.showcase.insightsame',
      SOURCING_VIEW: '/alphashop.agent-home-page.showcase.sourcingview',
      SOURCING_SAME: '/alphashop.agent-home-page.showcase.sourcingsame',
      DESIGN_CLICK: '/alphashop.agent-home-page.showcase.designclick',
      DESIGN_PB: '/alphashop.agent-home-page.showcase.designpb',
      DESIGN_SHARE: '/alphashop.agent-home-page.showcase.designshare',
      DESIGN_SAME: '/alphashop.agent-home-page.showcase.designsame',
      INQUIRY_VIEW: '/alphashop.agent-home-page.showcase.inquiryview',
      CHAT_SAME: '/alphashop.agent-home-page.showcase.chatsame',
      CHAT_VIEW: '/alphashop.agent-home-page.showcase.chatview',
    },
    LOGIN: {
      BUTTON: '/alphashop.agent-home-page.login.button',
    },
  },
  SELECT_PRODUCT_HOME: {
    SIDEBAR: {
      LOGO: '/alphashop.select-product-home-page.sidebar.logo',
      HOME: '/alphashop.select-product-home-page.sidebar.home',
      INSIGHT: '/alphashop.select-product-home-page.sidebar.insight',
      SOURCING: '/alphashop.select-product-home-page.sidebar.sourcing',
      DESIGN: '/alphashop.select-product-home-page.sidebar.design',
      INQUIRY: '/alphashop.select-product-home-page.sidebar.inquiry',
      CHAT: '/alphashop.select-product-home-page.sidebar.chat',
      SET: '/alphashop.select-product-home-page.sidebar.set',
      OPENPLATFORM: '/alphashop.select-product-home-page.sidebar.openplatform',
      HOT_RANKING: '/alphashop.agent-home-page.sidebar.rankinglist',
    },
    CHATBOX: {
      INSIGHT_CLICK: '/alphashop.select-product-home-page.chatbox.insightclick',
      INSIGHT_CHANNEL: '/alphashop.select-product-home-page.chatbox.insightchannel',
      INSIGHT_COUNTRY: '/alphashop.select-product-home-page.chatbox.insightcountry',
    },
    CARD: {
      INSIGHT_NEW: '/alphashop.select-product-home-page.card.insightnew',
      INSIGHT_COUNTRY: '/alphashop.select-product-home-page.card.insightcountry',
      INSIGHT_PLATFORM: '/alphashop.select-product-home-page.card.insightplayform',
      INSIGHT_IMPROVE: '/alphashop.select-product-home-page.card.insightimprove',
      IMG_SEARCH: '/alphashop.select-product-home-page.card.imgsearch',
    },
    SHOWCASE: {
      INSIGHT_VIEW: '/alphashop.select-product-home-page.showcase.insightview',
      INSIGHT_SAME: '/alphashop.select-product-home-page.showcase.insightsame',
    },
    RANKING: {
      OPPORTUNITY: '/alphashop.select-product-home-page.rankinglist.opportunity',
      ALL_ITEM: '/alphashop.select-product-home-page.rankinglist.allitem',
    },
    HISTORY: '/alphashop.select-product-home-page.history',
    LOGIN: {
      BUTTON: '/alphashop.select-product-home-page.login.button',
    },
  },
  SELECT_BUSINESS: {
    CHATBOX: {
      SOURCING_CLICK: '/alphashop.select-business-page.chatbox.sourcingclick',
      SOURCING_MODE: '/alphashop.select-business-page.chatbox.sourcingmode',
      SOURCING_IMG: '/alphashop.select-business-page.chatbox.sourcingimg',
    },
    SHOWCASE: {
      SOURCING_VIEW: '/alphashop.select-business-page.showcase.sourcingview',
      SOURCING_SAME: '/alphashop.select-business-page.showcase.sourcingsame',
    },
    HISTORY: {
      BUTTON: '/alphashop.select-business-page.history.button',
    },
    LOGIN: {
      BUTTON: '/alphashop.select-business-page.login.button',
    },
    LP: {
      SOURCING_CLICK: '/alphashop.select-business-page.lp.sourcingclick',
      CHAT_CLICK: '/alphashop.select-business-page.lp.chatclick',
      TITLE_CLICK: '/alphashop.select-business-page.lp.titleclick',
      SUPP_CLICK: '/alphashop.select-business-page.lp.suppclick',
      SHARE: '/alphashop.select-business-page.lp.share',
      DOWNLOAD: '/alphashop.select-business-page.lp.download',
      FEEDBACK: '/alphashop.select-business-page.lp.feedback',
    },
  },
  INQUIRY_HOME: {
    CHATBOX: {
      INQUIRY_CLICK: '/alphashop.inquiry-home.chatbox.inquiryclick',
    },
    MY_TASK: {
      ALL: '/alphashop.inquiry-home.mytask.all',
      DONE: '/alphashop.inquiry-home.mytask.done',
      DOING: '/alphashop.inquiry-home.mytask.doing',
      WAIT: '/alphashop.inquiry-home.mytask.wait',
      VIEW: '/alphashop.inquiry-home.mytask.view',
    },
    SUPP_LIST: {
      BUTTON: '/alphashop.inquiry-home.supplist.button',
    },
    LOGIN: {
      BUTTON: '/alphashop.inquiry-home.login.button',
    },
    LP: {
      INQUIRY_CLICK: '/alphashop.inquiry-home.lp.inquiryclick',
      ORI_TEXT: '/alphashop.inquiry-home.lp.oritext',
      GO_SOURCING: '/alphashop.inquiry-home.lp.gosourcing',
      REQUEST: '/alphashop.inquiry-home.lp.request',
      PROGRESS: '/alphashop.inquiry-home.lp.progress',
      REPORT: '/alphashop.inquiry-home.lp.report',
      SHARE: '/alphashop.inquiry-home.lp.share',
      UPLOAD_IMG: '/alphashop.inquiry-home.lp.uploadimg',
      ANALYSIS: '/alphashop.inquiry-home.lp.analysis',
      SUPP_LIST: '/alphashop.inquiry-home.lp.supplist',
      QUESTION: '/alphashop.inquiry-home.lp.question',
    },
    MANUAL: '/alphashop.inquiry-home.manual',
    SYNCHRONIZE: '/alphashop.inquiry-home.synchronize',
  },
  COMMON_CHAT: {
    CHATBOX: {
      CHAT_CLICK: '/alphashop.common-chat-page.chatbox.chatclick',
    },
    SHOWCASE: {
      CHAT_SAME: '/alphashop.common-chat-page.showcase.chatsame',
      CHAT_VIEW: '/alphashop.common-chat-page.showcase.chatview',
    },
    HISTORY: {
      BUTTON: '/alphashop.common-chat-page.history.button',
    },
    LOGIN: {
      BUTTON: '/alphashop.common-chat-page.login.button',
    },
    LP: {
      WEB_SEARCH: '/alphashop.common-chat-page.lp.websearch',
      CHATBOX_CLICK: '/alphashop.common-chat-page.lp.chatboxclick',
      NUM_CLICK: '/alphashop.common-chat-page.lp.numclick',
      SHARE: '/alphashop.common-chat-page.lp.share',
      DOWNLOAD: '/alphashop.common-chat-page.lp.download',
      FEEDBACK: '/alphashop.common-chat-page.lp.feedback',
    },
  },
  GENERAL_AGENT: {
    LP: {
      CONFIRM: '/alphashop.general-agent-page.lp.confirm',
      CHAT_CLICK: '/alphashop.general-agent-page.lp.chatclick',
      KEYWORD: '/alphashop.general-agent-page.lp.keyword',
      ITEM_LIST: '/alphashop.general-agent-page.lp.itemlist',
      ANA_OPP: '/alphashop.general-agent-page.lp.anaopp',
      SWITCH_KEYWORD: '/alphashop.general-agent-page.lp.switchkeyword',
      GO_INQUIRY: '/alphashop.general-agent-page.lp.goinquiry',
      GO_DESIGN: '/alphashop.general-agent-page.lp.godesign',
      ITEM_TITLE: '/alphashop.general-agent-page.lp.itemtitle',
      TABLE_URL: '/alphashop.general-agent-page.lp.tableurl',
      SHARE: '/alphashop.general-agent-page.lp.share',
      DOWNLOAD: '/alphashop.general-agent-page.lp.download',
      FEEDBACK: '/alphashop.general-agent-page.lp.feedback',
      // 按钮点击埋点
      KEYWORD_DETAIL: '/alphashop.general-agent-page.lp.keyworddetail',
      KEYWORD_MARKET_ANALYSIS: '/alphashop.general-agent-page.lp.keywordmarket',
      KEYWORD_REVIEW: '/alphashop.general-agent-page.lp.keywordreview',
      TOOL_RANK_PRODUCT: '/alphashop.general-agent-page.lp.toolrankproduct',
      ORIGINAL_REVIEW: '/alphashop.general-agent-page.lp.originalreview',
      INPUT_WORD_CATE: '/alphashop.general-agent-page.lp.inputwordcate',
      KEYWORD_GOOGLE_TRENDS: '/alphashop.general-agent-page.lp.keywordgoogle',
      CATE_GOOGLE_TRENDS: '/alphashop.general-agent-page.lp.categoogle',
      CATE_TIKTOK_TRENDS: '/alphashop.general-agent-page.lp.catetiktok',
      KEYWORD_AMAZON_TRENDS: '/alphashop.general-agent-page.lp.keywordamazon',
      REPORT_CARD: '/alphashop.general-agent-page.lp.reportcard',
      FOLLOW_UP: '/alphashop.general-agent-page.lp.followup',
      SELECT_KEYWORD: '/alphashop.general-agent-page.lp.selectkeyword',
      VIEW_KEYWORD_DATA: '/alphashop.general-agent-page.lp.viewkeyworddata',
      SUPPLIER_MORE: '/alphashop.general-agent-page.lp.suppliermore',
      MATERIAL_PROCESS: '/alphashop.general-agent-page.lp.materialprocess',
      PRODUCT_DETAIL: '/alphashop.general-agent-page.lp.productdetail',
      TABLE_PRODUCT_CLICK: '/alphashop.general-agent-page.lp.tableproductclick',
      EXPORT_REPORT: '/alphashop.general-agent-page.lp.exportreport',
      ITEMLIST_IMGCLICK: '/alphashop.general-agent-page.lp.itemlist.imgclick',
      OPP_SCORE_HOVER: '/alphashop.general-agent-page.lp.oppscorehover',
      PRODUCT_IMG_HOVER: '/alphashop.general-agent-page.lp.productimghover',
      PRODUCT_SALES_HOVER: '/alphashop.general-agent-page.lp.productsaleshover',
      PRODUCT_RATING_HOVER: '/alphashop.general-agent-page.lp.productratinghover',
      PRODUCT_SKU_HOVER: '/alphashop.general-agent-page.lp.productskuhover',
      SERVICE_CAPABILITY_HOVER: '/alphashop.general-agent-page.lp.servicecapabilityhover',
      REPORT_ITEMCARD: '/alphashop.general-agent-page.lp.reportitemcard',
    },
    RECOMMEND: {
      SUPPLIER_HOME: '/alphashop.general-agent-page.recommend.supplierhome',
      OD_PAGE: '/alphashop.general-agent-page.recommend.odpage',
    },
  },
  NEW_PRODUCT_AGENT: {
    LP: {
      CONFIRM: '/alphashop.opportunity-new-product-agent-page.lp.confirm',
      KEYWORD: '/alphashop.opportunity-new-product-agent-page.lp.keyword',
      ITEM_LIST: '/alphashop.opportunity-new-product-agent-page.lp.itemlist',
      ANA_OPP: '/alphashop.opportunity-new-product-agent-page.lp.anaopp',
      SWITCH_KEYWORD: '/alphashop.opportunity-new-product-agent-page.lp.switchkeyword',
      GO_INQUIRY: '/alphashop.opportunity-new-product-agent-page.lp.goinquiry',
      GO_DESIGN: '/alphashop.opportunity-new-product-agent-page.lp.godesign',
      SHARE: '/alphashop.opportunity-new-product-agent-page.lp.share',
      DOWNLOAD: '/alphashop.opportunity-new-product-agent-page.lp.download',
      // 按钮点击埋点
      KEYWORD_SELECT_CARD: '/alphashop.opportunity-new-product-agent-page.lp.keywordselectcard',
      KEYWORD_GOOGLE_TRENDS: '/alphashop.opportunity-new-product-agent-page.lp.keywordgoogle',
      CATE_GOOGLE_TRENDS: '/alphashop.opportunity-new-product-agent-page.lp.categoogle',
      CATE_SELECT_CARD: '/alphashop.opportunity-new-product-agent-page.lp.cateselectcard',
      REPORT_CARD: '/alphashop.opportunity-new-product-agent-page.lp.reportcard',
      SELECT_KEYWORD: '/alphashop.opportunity-new-product-agent-page.lp.selectkeyword',
      VIEW_KEYWORD_DATA: '/alphashop.opportunity-new-product-agent-page.lp.viewkeyworddata',
      HOT_DETAIL: '/alphashop.opportunity-new-product-agent-page.lp.hotdetail',
      COMPARED_DETAIL: '/alphashop.opportunity-new-product-agent-page.lp.compareddetail',
      NORMAL_PRODUCT: '/alphashop.opportunity-new-product-agent-page.lp.normalproduct',
      NEW_PRODUCT: '/alphashop.opportunity-new-product-agent-page.lp.newproduct',
      HOT_SALE_PRODUCT: '/alphashop.opportunity-new-product-agent-page.lp.hotsaleproduct',
      COMPARED_PRODUCT: '/alphashop.opportunity-new-product-agent-page.lp.comparedproduct',
      MODIFY_FORM: '/alphashop.opportunity-new-product-agent-page.lp.modifyform',
      EXPORT_REPORT: '/alphashop.opportunity-new-product-agent-page.lp.exportreport',
      ITEMLIST_IMGCLICK: '/alphashop.newproduct-agent-page.lp.itemlist.imgclick',
      REPORT_ITEMCARD_IMGCLICK: '/alphashop.newproduct-agent-page.report.itemcard.imgclick',
      REPORT_ITEMCARD_TITLECLICK: '/alphashop.newproduct-agent-page.report.itemcard.titleclick',
      FIND_SIMILAR_SUPPLIER: '/alphashop.newproduct-agent-page.lp.findsimilarsupplier',
    },
  },
  IMPROVE_AGENT: {
    LP: {
      CONFIRM: '/alphashop.improve-agent-page.lp.confirm',
      KEYWORD: '/alphashop.improve-agent-page.lp.keyword',
      ITEM_LIST: '/alphashop.improve-agent-page.lp.itemlist',
      ANA_OPP: '/alphashop.improve-agent-page.lp.anaopp',
      SWITCH_KEYWORD: '/alphashop.improve-agent-page.lp.switchkeyword',
      GO_INQUIRY: '/alphashop.improve-agent-page.lp.goinquiry',
      GO_DESIGN: '/alphashop.improve-agent-page.lp.godesign',
      SHARE: '/alphashop.improve-agent-page.lp.share',
      DOWNLOAD: '/alphashop.improve-agent-page.lp.download',
      // 按钮点击埋点
      KEYWORD_SELECT_CARD: '/alphashop.improve-agent-page.lp.keywordselectcard',
      KEYWORD_GOOGLE_TRENDS: '/alphashop.improve-agent-page.lp.keywordgoogle',
      CATE_GOOGLE_TRENDS: '/alphashop.improve-agent-page.lp.categoogle',
      CATE_SELECT_CARD: '/alphashop.improve-agent-page.lp.cateselectcard',
      KEYWORD_AMAZON_TRENDS: '/alphashop.improve-agent-page.lp.keywordamazon',
      CATE_TIKTOK_TRENDS: '/alphashop.improve-agent-page.lp.catetiktok',
      PRODUCT_IMPROVE_COMMENT_TAGS: '/alphashop.improve-agent-page.lp.commenttags',
      COMMENT_TAGS: '/alphashop.improve-agent-page.lp.commenttags',
      REPORT_CARD: '/alphashop.improve-agent-page.lp.reportcard',
      SELECT_KEYWORD: '/alphashop.improve-agent-page.lp.selectkeyword',
      VIEW_KEYWORD_DATA: '/alphashop.improve-agent-page.lp.viewkeyworddata',
      ANALYSIS_DETAIL: '/alphashop.improve-agent-page.lp.analysisdetail',
      ANALYSIS_PRODUCT: '/alphashop.improve-agent-page.lp.analysisproduct',
      REVIEWED_PRODUCT: '/alphashop.improve-agent-page.lp.reviewedproduct',
      IMPROVE_CHOICE_KEYWORD: '/alphashop.improve-agent-page.lp.improvechoicekeyword',
      IMPROVE_CHOICE_CATE: '/alphashop.improve-agent-page.lp.improvechoicecate',
      MODIFY_FORM: '/alphashop.improve-agent-page.lp.modifyform',
      EXPORT_REPORT: '/alphashop.improve-agent-page.lp.exportreport',
    },
  },
  COUNTRY_AGENT: {
    LP: {
      CONFIRM: '/alphashop.country-agent-page.lp.confirm',
      KEYWORD: '/alphashop.country-agent-page.lp.keyword',
      ITEM_LIST: '/alphashop.country-agent-page.lp.itemlist',
      ANA_OPP: '/alphashop.country-agent-page.lp.anaopp',
      SWITCH_KEYWORD: '/alphashop.country-agent-page.lp.switchkeyword',
      GO_INQUIRY: '/alphashop.country-agent-page.lp.goinquiry',
      GO_DESIGN: '/alphashop.country-agent-page.lp.godesign',
      SHARE: '/alphashop.country-agent-page.lp.share',
      DOWNLOAD: '/alphashop.country-agent-page.lp.download',
      // 按钮点击埋点
      KEYWORD_SELECT_CARD: '/alphashop.country-agent-page.lp.keywordselectcard',
      KEYWORD_GOOGLE_TRENDS: '/alphashop.country-agent-page.lp.keywordgoogle',
      CATE_GOOGLE_TRENDS: '/alphashop.country-agent-page.lp.categoogle',
      CATE_SELECT_CARD: '/alphashop.country-agent-page.lp.cateselectcard',
      REPORT_CARD: '/alphashop.country-agent-page.lp.reportcard',
      SELECT_KEYWORD: '/alphashop.country-agent-page.lp.selectkeyword',
      VIEW_KEYWORD_DATA: '/alphashop.country-agent-page.lp.viewkeyworddata',
      MIGRATED_DETAIL: '/alphashop.country-agent-page.lp.migrateddetail',
      COMPARED_DETAIL: '/alphashop.country-agent-page.lp.compareddetail',
      MIGRATED_CHOICE_KEYWORD: '/alphashop.country-agent-page.lp.migratedchoicekeyword',
      MIGRATED_CHOICE_CATE: '/alphashop.country-agent-page.lp.migratedchoicecate',
      MIGRATE_CHOICE_KEYWORD: '/alphashop.country-agent-page.lp.migratechoicekeyword',
      NORMAL_PRODUCT: '/alphashop.country-agent-page.lp.normalproduct',
      MIGRATED_PRODUCT: '/alphashop.country-agent-page.lp.migratedproduct',
      SCORE_PRODUCT: '/alphashop.country-agent-page.lp.scoreproduct',
      ANALYSIS_PRODUCT: '/alphashop.country-agent-page.lp.analysisproduct',
      MODIFY_FORM: '/alphashop.country-agent-page.lp.modifyform',
      EXPORT_REPORT: '/alphashop.country-agent-page.lp.exportreport',
    },
  },
  PLATFORM_AGENT: {
    LP: {
      CONFIRM: '/alphashop.platform-agent-page.lp.confirm',
      KEYWORD: '/alphashop.platform-agent-page.lp.keyword',
      ITEM_LIST: '/alphashop.platform-agent-page.lp.itemlist',
      ANA_OPP: '/alphashop.platform-agent-page.lp.anaopp',
      SWITCH_KEYWORD: '/alphashop.platform-agent-page.lp.switchkeyword',
      GO_INQUIRY: '/alphashop.platform-agent-page.lp.goinquiry',
      GO_DESIGN: '/alphashop.platform-agent-page.lp.godesign',
      SHARE: '/alphashop.platform-agent-page.lp.share',
      DOWNLOAD: '/alphashop.platform-agent-page.lp.download',
      // 按钮点击埋点
      KEYWORD_SELECT_CARD: '/alphashop.platform-agent-page.lp.keywordselectcard',
      KEYWORD_GOOGLE_TRENDS: '/alphashop.platform-agent-page.lp.keywordgoogle',
      CATE_GOOGLE_TRENDS: '/alphashop.platform-agent-page.lp.categoogle',
      CATE_SELECT_CARD: '/alphashop.platform-agent-page.lp.cateselectcard',
      REPORT_CARD: '/alphashop.platform-agent-page.lp.reportcard',
      SELECT_KEYWORD: '/alphashop.platform-agent-page.lp.selectkeyword',
      VIEW_KEYWORD_DATA: '/alphashop.platform-agent-page.lp.viewkeyworddata',
      MIGRATED_DETAIL: '/alphashop.platform-agent-page.lp.migrateddetail',
      COMPARED_DETAIL: '/alphashop.platform-agent-page.lp.compareddetail',
      MIGRATED_CHOICE_KEYWORD: '/alphashop.platform-agent-page.lp.migratedchoicekeyword',
      MIGRATED_CHOICE_CATE: '/alphashop.platform-agent-page.lp.migratedchoicecate',
      MIGRATE_CHOICE_KEYWORD: '/alphashop.platform-agent-page.lp.migratechoicekeyword',
      NORMAL_PRODUCT: '/alphashop.platform-agent-page.lp.normalproduct',
      MIGRATED_PRODUCT: '/alphashop.platform-agent-page.lp.migratedproduct',
      SCORE_PRODUCT: '/alphashop.platform-agent-page.lp.scoreproduct',
      ANALYSIS_PRODUCT: '/alphashop.platform-agent-page.lp.analysisproduct',
      MODIFY_FORM: '/alphashop.platform-agent-page.lp.modifyform',
      EXPORT_REPORT: '/alphashop.platform-agent-page.lp.exportreport',
    },
  },
  IMAGE_SEARCH_AGENT: {
    LP: {
      FOLLOW_UP: '/alphashop.image-search-page.lp.followup',
    },
  },
  LOGIN: {
    LOGIN_BUTTON: '/alphashop.login.login.button',
    LOG_TYPE_BUTTON: '/alphashop.login.logtype.button',
  },
  RANKINGLIST: {
    LIST_CLICK: {
      OPPORTUNITY: '/alphashop.rankinglist.listclick.opportunity',
      ALLITEM: '/alphashop.rankinglist.listclick.allitem',
    },
    OPPORTUNITY: {
      TRACK_ANALYSIS: '/alphashop.rankinglist.opportunity.trackanalysis',
      SOURCING_1688: '/alphashop.rankinglist.opportunity.1688sourcing',
      LIST_DETAIL: '/alphashop.rankinglist.opportunity.listdetail',
      COUNTRY_SELECT: '/alphashop.rankinglist.opportunity.countryselect',
    },
    TRACK_ANALYSIS: {
      ITEM_IMG_CLICK: '/alphashop.rankinglist.trackanalysis.itemimgclick',
      MORE: '/alphashop.rankinglist.trackanalysis.more',
    },
    SOURCING: {
      REPORT: '/alphashop.rankinglist.sourcing.report',
      SELECT: '/alphashop.rankinglist.sourcing.select',
      INQUIRY: '/alphashop.rankinglist.sourcing.inqury',
      DESIGN: '/alphashop.rankinglist.sourcing.design',
    },
    LOGIN: '/alphashop.rankinglist.login',
    SIDEBAR: {
      CATE: '/alphashop.rankinglist.sidebar.cate',
      TIME: '/alphashop.rankinglist.sidebar.time',
      CHANNEL: '/alphashop.rankinglist.sidebar.channel',
    },
  },
} as const;

export type TypeLogKeyValue = typeof LOG_KEYS[keyof typeof LOG_KEYS];