import { contanst } from "@alife/1688-chain-renderfield";

const {
  SCHEMA_INPUT,
  SCHEMA_SELECT,
  SCHEMA_RANGE_PICKER,
  SCHEMA_DATE_PICKER,
  SCHEMA_SEARCH,
  SCHEMA_BARCODE,
  SCHEMA_CHECKBOX,
  SCHEMA_TREE_SELECT,
  SCHEMA_TEXTAREA,
  SCHEMA_SELECT_CARDS,
} = contanst;

export {
  SCHEMA_INPUT,
  SCHEMA_SELECT,
  SCHEMA_RANGE_PICKER,
  SCHEMA_DATE_PICKER,
  SCHEMA_SEARCH,
  SCHEMA_BARCODE,
  SCHEMA_CHECKBOX,
  SCHEMA_TREE_SELECT,
  SCHEMA_TEXTAREA,
  SCHEMA_SELECT_CARDS,
};
